package com.ultarischool.utprogramclass;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class utprogramclassExample extends  PageVO{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public utprogramclassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(Integer value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(Integer value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(Integer value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(Integer value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(Integer value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<Integer> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<Integer> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(Integer value1, Integer value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(Integer value1, Integer value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkIsNull() {
            addCriterion("utprogramchafk is null");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkIsNotNull() {
            addCriterion("utprogramchafk is not null");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkEqualTo(Integer value) {
            addCriterion("utprogramchafk =", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkNotEqualTo(Integer value) {
            addCriterion("utprogramchafk <>", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkGreaterThan(Integer value) {
            addCriterion("utprogramchafk >", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkGreaterThanOrEqualTo(Integer value) {
            addCriterion("utprogramchafk >=", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkLessThan(Integer value) {
            addCriterion("utprogramchafk <", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkLessThanOrEqualTo(Integer value) {
            addCriterion("utprogramchafk <=", value, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkIn(List<Integer> values) {
            addCriterion("utprogramchafk in", values, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkNotIn(List<Integer> values) {
            addCriterion("utprogramchafk not in", values, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkBetween(Integer value1, Integer value2) {
            addCriterion("utprogramchafk between", value1, value2, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andUtprogramchafkNotBetween(Integer value1, Integer value2) {
            addCriterion("utprogramchafk not between", value1, value2, "utprogramchafk");
            return (Criteria) this;
        }

        public Criteria andClassnameIsNull() {
            addCriterion("classname is null");
            return (Criteria) this;
        }

        public Criteria andClassnameIsNotNull() {
            addCriterion("classname is not null");
            return (Criteria) this;
        }

        public Criteria andClassnameEqualTo(String value) {
            addCriterion("classname =", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotEqualTo(String value) {
            addCriterion("classname <>", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameGreaterThan(String value) {
            addCriterion("classname >", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameGreaterThanOrEqualTo(String value) {
            addCriterion("classname >=", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLessThan(String value) {
            addCriterion("classname <", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLessThanOrEqualTo(String value) {
            addCriterion("classname <=", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameLike(String value) {
            addCriterion("classname like", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotLike(String value) {
            addCriterion("classname not like", value, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameIn(List<String> values) {
            addCriterion("classname in", values, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotIn(List<String> values) {
            addCriterion("classname not in", values, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameBetween(String value1, String value2) {
            addCriterion("classname between", value1, value2, "classname");
            return (Criteria) this;
        }

        public Criteria andClassnameNotBetween(String value1, String value2) {
            addCriterion("classname not between", value1, value2, "classname");
            return (Criteria) this;
        }

        public Criteria andJobodeIsNull() {
            addCriterion("jobode is null");
            return (Criteria) this;
        }

        public Criteria andJobodeIsNotNull() {
            addCriterion("jobode is not null");
            return (Criteria) this;
        }

        public Criteria andJobodeEqualTo(String value) {
            addCriterion("jobode =", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeNotEqualTo(String value) {
            addCriterion("jobode <>", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeGreaterThan(String value) {
            addCriterion("jobode >", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeGreaterThanOrEqualTo(String value) {
            addCriterion("jobode >=", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeLessThan(String value) {
            addCriterion("jobode <", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeLessThanOrEqualTo(String value) {
            addCriterion("jobode <=", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeLike(String value) {
            addCriterion("jobode like", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeNotLike(String value) {
            addCriterion("jobode not like", value, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeIn(List<String> values) {
            addCriterion("jobode in", values, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeNotIn(List<String> values) {
            addCriterion("jobode not in", values, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeBetween(String value1, String value2) {
            addCriterion("jobode between", value1, value2, "jobode");
            return (Criteria) this;
        }

        public Criteria andJobodeNotBetween(String value1, String value2) {
            addCriterion("jobode not between", value1, value2, "jobode");
            return (Criteria) this;
        }

        public Criteria andClassodrnoIsNull() {
            addCriterion("classodrno is null");
            return (Criteria) this;
        }

        public Criteria andClassodrnoIsNotNull() {
            addCriterion("classodrno is not null");
            return (Criteria) this;
        }

        public Criteria andClassodrnoEqualTo(String value) {
            addCriterion("classodrno =", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoNotEqualTo(String value) {
            addCriterion("classodrno <>", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoGreaterThan(String value) {
            addCriterion("classodrno >", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoGreaterThanOrEqualTo(String value) {
            addCriterion("classodrno >=", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoLessThan(String value) {
            addCriterion("classodrno <", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoLessThanOrEqualTo(String value) {
            addCriterion("classodrno <=", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoLike(String value) {
            addCriterion("classodrno like", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoNotLike(String value) {
            addCriterion("classodrno not like", value, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoIn(List<String> values) {
            addCriterion("classodrno in", values, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoNotIn(List<String> values) {
            addCriterion("classodrno not in", values, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoBetween(String value1, String value2) {
            addCriterion("classodrno between", value1, value2, "classodrno");
            return (Criteria) this;
        }

        public Criteria andClassodrnoNotBetween(String value1, String value2) {
            addCriterion("classodrno not between", value1, value2, "classodrno");
            return (Criteria) this;
        }

        public Criteria andLimithmIsNull() {
            addCriterion("limithm is null");
            return (Criteria) this;
        }

        public Criteria andLimithmIsNotNull() {
            addCriterion("limithm is not null");
            return (Criteria) this;
        }

        public Criteria andLimithmEqualTo(Integer value) {
            addCriterion("limithm =", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmNotEqualTo(Integer value) {
            addCriterion("limithm <>", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmGreaterThan(Integer value) {
            addCriterion("limithm >", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmGreaterThanOrEqualTo(Integer value) {
            addCriterion("limithm >=", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmLessThan(Integer value) {
            addCriterion("limithm <", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmLessThanOrEqualTo(Integer value) {
            addCriterion("limithm <=", value, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmIn(List<Integer> values) {
            addCriterion("limithm in", values, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmNotIn(List<Integer> values) {
            addCriterion("limithm not in", values, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmBetween(Integer value1, Integer value2) {
            addCriterion("limithm between", value1, value2, "limithm");
            return (Criteria) this;
        }

        public Criteria andLimithmNotBetween(Integer value1, Integer value2) {
            addCriterion("limithm not between", value1, value2, "limithm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utprogramclass
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utprogramclass
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}