package com.ultarischool.utprogramclass;

public class utprogramclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.utprogramchafk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer utprogramchafk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.classname
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.jobode
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String jobode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.classodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String classodrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utprogramclass.limithm
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer limithm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.sn
     *
     * @return the value of utprogramclass.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.sn
     *
     * @param sn the value for utprogramclass.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.utprogramchafk
     *
     * @return the value of utprogramclass.utprogramchafk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getUtprogramchafk() {
        return utprogramchafk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.utprogramchafk
     *
     * @param utprogramchafk the value for utprogramclass.utprogramchafk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setUtprogramchafk(Integer utprogramchafk) {
        this.utprogramchafk = utprogramchafk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.classname
     *
     * @return the value of utprogramclass.classname
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.classname
     *
     * @param classname the value for utprogramclass.classname
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.jobode
     *
     * @return the value of utprogramclass.jobode
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getJobode() {
        return jobode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.jobode
     *
     * @param jobode the value for utprogramclass.jobode
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setJobode(String jobode) {
        this.jobode = jobode == null ? null : jobode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.classodrno
     *
     * @return the value of utprogramclass.classodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getClassodrno() {
        return classodrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.classodrno
     *
     * @param classodrno the value for utprogramclass.classodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setClassodrno(String classodrno) {
        this.classodrno = classodrno == null ? null : classodrno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utprogramclass.limithm
     *
     * @return the value of utprogramclass.limithm
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getLimithm() {
        return limithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utprogramclass.limithm
     *
     * @param limithm the value for utprogramclass.limithm
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setLimithm(Integer limithm) {
        this.limithm = limithm;
    }
}