package com.ultarischool.usert;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class usertExample extends PageVO {
	
	private String logindate;
	public String getLogindate() {
		return logindate;
	}

	public void setLogindate(String logindate) {
		this.logindate = logindate;
	}

	public String getCucnt() {
		return cucnt;
	}

	public void setCucnt(String cucnt) {
		this.cucnt = cucnt;
	}

	private String cucnt;

	private String ttcnt;

	public String getTtcnt() {
		return ttcnt;
	}

	public void setTtcnt(String ttcnt) {
		this.ttcnt = ttcnt;
	}

	private String usertypecode;
	private String code2;

	public String getUsertypecode() {
		return usertypecode;
	}

	public void setUsertypecode(String usertypecode) {
		this.usertypecode = usertypecode;
	}

	public String getCode2() {
		return code2;
	}

	public void setCode2(String code2) {
		this.code2 = code2;
	}

	public String getUtjcode() {
		return utjcode;
	}

	public void setUtjcode(String utjcode) {
		this.utjcode = utjcode;
	}

	private String utjcode = "";

	private String utjcode1 = "";

	public String getUtjcode1() {
		return utjcode1;
	}

	public void setUtjcode1(String utjcode1) {
		this.utjcode1 = utjcode1;
	}

	public String getUtjcode2() {
		return utjcode2;
	}

	public void setUtjcode2(String utjcode2) {
		this.utjcode2 = utjcode2;
	}

	public String getUtjcode3() {
		return utjcode3;
	}

	public void setUtjcode3(String utjcode3) {
		this.utjcode3 = utjcode3;
	}

	private String utjcode2 = "";
	private String utjcode3 = "";

	private String usertype = "";

	public String getUsertype() {
		return usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public usertExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSnIsNull() {
			addCriterion("sn is null");
			return (Criteria) this;
		}

		public Criteria andSnIsNotNull() {
			addCriterion("sn is not null");
			return (Criteria) this;
		}

		public Criteria andSnEqualTo(Integer value) {
			addCriterion("sn =", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotEqualTo(Integer value) {
			addCriterion("sn <>", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThan(Integer value) {
			addCriterion("sn >", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThanOrEqualTo(Integer value) {
			addCriterion("sn >=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThan(Integer value) {
			addCriterion("sn <", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThanOrEqualTo(Integer value) {
			addCriterion("sn <=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnIn(List<Integer> values) {
			addCriterion("sn in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotIn(List<Integer> values) {
			addCriterion("sn not in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnBetween(Integer value1, Integer value2) {
			addCriterion("sn between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotBetween(Integer value1, Integer value2) {
			addCriterion("sn not between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userid like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userid not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkIsNull() {
			addCriterion("schoolunivfk is null");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkIsNotNull() {
			addCriterion("schoolunivfk is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkEqualTo(Integer value) {
			addCriterion("schoolunivfk =", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkNotEqualTo(Integer value) {
			addCriterion("schoolunivfk <>", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkGreaterThan(Integer value) {
			addCriterion("schoolunivfk >", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkGreaterThanOrEqualTo(Integer value) {
			addCriterion("schoolunivfk >=", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkLessThan(Integer value) {
			addCriterion("schoolunivfk <", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkLessThanOrEqualTo(Integer value) {
			addCriterion("schoolunivfk <=", value, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkIn(List<Integer> values) {
			addCriterion("schoolunivfk in", values, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkNotIn(List<Integer> values) {
			addCriterion("schoolunivfk not in", values, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkBetween(Integer value1, Integer value2) {
			addCriterion("schoolunivfk between", value1, value2, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andSchoolunivfkNotBetween(Integer value1, Integer value2) {
			addCriterion("schoolunivfk not between", value1, value2, "schoolunivfk");
			return (Criteria) this;
		}

		public Criteria andUserpwIsNull() {
			addCriterion("userpw is null");
			return (Criteria) this;
		}

		public Criteria andUserpwIsNotNull() {
			addCriterion("userpw is not null");
			return (Criteria) this;
		}

		public Criteria andUserpwEqualTo(String value) {
			addCriterion("userpw =", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwNotEqualTo(String value) {
			addCriterion("userpw <>", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwGreaterThan(String value) {
			addCriterion("userpw >", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwGreaterThanOrEqualTo(String value) {
			addCriterion("userpw >=", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwLessThan(String value) {
			addCriterion("userpw <", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwLessThanOrEqualTo(String value) {
			addCriterion("userpw <=", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwLike(String value) {
			addCriterion("userpw like", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwNotLike(String value) {
			addCriterion("userpw not like", value, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwIn(List<String> values) {
			addCriterion("userpw in", values, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwNotIn(List<String> values) {
			addCriterion("userpw not in", values, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwBetween(String value1, String value2) {
			addCriterion("userpw between", value1, value2, "userpw");
			return (Criteria) this;
		}

		public Criteria andUserpwNotBetween(String value1, String value2) {
			addCriterion("userpw not between", value1, value2, "userpw");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNull() {
			addCriterion("usertype is null");
			return (Criteria) this;
		}

		public Criteria andUsertypeIsNotNull() {
			addCriterion("usertype is not null");
			return (Criteria) this;
		}

		public Criteria andUsertypeEqualTo(String value) {
			addCriterion("usertype =", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotEqualTo(String value) {
			addCriterion("usertype <>", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThan(String value) {
			addCriterion("usertype >", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeGreaterThanOrEqualTo(String value) {
			addCriterion("usertype >=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThan(String value) {
			addCriterion("usertype <", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLessThanOrEqualTo(String value) {
			addCriterion("usertype <=", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeLike(String value) {
			addCriterion("usertype like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotLike(String value) {
			addCriterion("usertype not like", value, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeIn(List<String> values) {
			addCriterion("usertype in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotIn(List<String> values) {
			addCriterion("usertype not in", values, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeBetween(String value1, String value2) {
			addCriterion("usertype between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andUsertypeNotBetween(String value1, String value2) {
			addCriterion("usertype not between", value1, value2, "usertype");
			return (Criteria) this;
		}

		public Criteria andSnstypeIsNull() {
			addCriterion("snstype is null");
			return (Criteria) this;
		}

		public Criteria andSnstypeIsNotNull() {
			addCriterion("snstype is not null");
			return (Criteria) this;
		}

		public Criteria andSnstypeEqualTo(String value) {
			addCriterion("snstype =", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeNotEqualTo(String value) {
			addCriterion("snstype <>", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeGreaterThan(String value) {
			addCriterion("snstype >", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeGreaterThanOrEqualTo(String value) {
			addCriterion("snstype >=", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeLessThan(String value) {
			addCriterion("snstype <", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeLessThanOrEqualTo(String value) {
			addCriterion("snstype <=", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeLike(String value) {
			addCriterion("snstype like", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeNotLike(String value) {
			addCriterion("snstype not like", value, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeIn(List<String> values) {
			addCriterion("snstype in", values, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeNotIn(List<String> values) {
			addCriterion("snstype not in", values, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeBetween(String value1, String value2) {
			addCriterion("snstype between", value1, value2, "snstype");
			return (Criteria) this;
		}

		public Criteria andSnstypeNotBetween(String value1, String value2) {
			addCriterion("snstype not between", value1, value2, "snstype");
			return (Criteria) this;
		}

		public Criteria andUsyearIsNull() {
			addCriterion("usyear is null");
			return (Criteria) this;
		}

		public Criteria andUsyearIsNotNull() {
			addCriterion("usyear is not null");
			return (Criteria) this;
		}

		public Criteria andUsyearEqualTo(String value) {
			addCriterion("usyear =", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearNotEqualTo(String value) {
			addCriterion("usyear <>", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearGreaterThan(String value) {
			addCriterion("usyear >", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearGreaterThanOrEqualTo(String value) {
			addCriterion("usyear >=", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearLessThan(String value) {
			addCriterion("usyear <", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearLessThanOrEqualTo(String value) {
			addCriterion("usyear <=", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearLike(String value) {
			addCriterion("usyear like", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearNotLike(String value) {
			addCriterion("usyear not like", value, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearIn(List<String> values) {
			addCriterion("usyear in", values, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearNotIn(List<String> values) {
			addCriterion("usyear not in", values, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearBetween(String value1, String value2) {
			addCriterion("usyear between", value1, value2, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsyearNotBetween(String value1, String value2) {
			addCriterion("usyear not between", value1, value2, "usyear");
			return (Criteria) this;
		}

		public Criteria andUsbanIsNull() {
			addCriterion("usban is null");
			return (Criteria) this;
		}

		public Criteria andUsbanIsNotNull() {
			addCriterion("usban is not null");
			return (Criteria) this;
		}

		public Criteria andUsbanEqualTo(String value) {
			addCriterion("usban =", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanNotEqualTo(String value) {
			addCriterion("usban <>", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanGreaterThan(String value) {
			addCriterion("usban >", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanGreaterThanOrEqualTo(String value) {
			addCriterion("usban >=", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanLessThan(String value) {
			addCriterion("usban <", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanLessThanOrEqualTo(String value) {
			addCriterion("usban <=", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanLike(String value) {
			addCriterion("usban like", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanNotLike(String value) {
			addCriterion("usban not like", value, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanIn(List<String> values) {
			addCriterion("usban in", values, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanNotIn(List<String> values) {
			addCriterion("usban not in", values, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanBetween(String value1, String value2) {
			addCriterion("usban between", value1, value2, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbanNotBetween(String value1, String value2) {
			addCriterion("usban not between", value1, value2, "usban");
			return (Criteria) this;
		}

		public Criteria andUsbunIsNull() {
			addCriterion("usbun is null");
			return (Criteria) this;
		}

		public Criteria andUsbunIsNotNull() {
			addCriterion("usbun is not null");
			return (Criteria) this;
		}

		public Criteria andUsbunEqualTo(String value) {
			addCriterion("usbun =", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunNotEqualTo(String value) {
			addCriterion("usbun <>", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunGreaterThan(String value) {
			addCriterion("usbun >", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunGreaterThanOrEqualTo(String value) {
			addCriterion("usbun >=", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunLessThan(String value) {
			addCriterion("usbun <", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunLessThanOrEqualTo(String value) {
			addCriterion("usbun <=", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunLike(String value) {
			addCriterion("usbun like", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunNotLike(String value) {
			addCriterion("usbun not like", value, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunIn(List<String> values) {
			addCriterion("usbun in", values, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunNotIn(List<String> values) {
			addCriterion("usbun not in", values, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunBetween(String value1, String value2) {
			addCriterion("usbun between", value1, value2, "usbun");
			return (Criteria) this;
		}

		public Criteria andUsbunNotBetween(String value1, String value2) {
			addCriterion("usbun not between", value1, value2, "usbun");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andNotiemailIsNull() {
			addCriterion("notiemail is null");
			return (Criteria) this;
		}

		public Criteria andNotiemailIsNotNull() {
			addCriterion("notiemail is not null");
			return (Criteria) this;
		}

		public Criteria andNotiemailEqualTo(String value) {
			addCriterion("notiemail =", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailNotEqualTo(String value) {
			addCriterion("notiemail <>", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailGreaterThan(String value) {
			addCriterion("notiemail >", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailGreaterThanOrEqualTo(String value) {
			addCriterion("notiemail >=", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailLessThan(String value) {
			addCriterion("notiemail <", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailLessThanOrEqualTo(String value) {
			addCriterion("notiemail <=", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailLike(String value) {
			addCriterion("notiemail like", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailNotLike(String value) {
			addCriterion("notiemail not like", value, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailIn(List<String> values) {
			addCriterion("notiemail in", values, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailNotIn(List<String> values) {
			addCriterion("notiemail not in", values, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailBetween(String value1, String value2) {
			addCriterion("notiemail between", value1, value2, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiemailNotBetween(String value1, String value2) {
			addCriterion("notiemail not between", value1, value2, "notiemail");
			return (Criteria) this;
		}

		public Criteria andNotiesmsIsNull() {
			addCriterion("notiesms is null");
			return (Criteria) this;
		}

		public Criteria andNotiesmsIsNotNull() {
			addCriterion("notiesms is not null");
			return (Criteria) this;
		}

		public Criteria andNotiesmsEqualTo(String value) {
			addCriterion("notiesms =", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsNotEqualTo(String value) {
			addCriterion("notiesms <>", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsGreaterThan(String value) {
			addCriterion("notiesms >", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsGreaterThanOrEqualTo(String value) {
			addCriterion("notiesms >=", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsLessThan(String value) {
			addCriterion("notiesms <", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsLessThanOrEqualTo(String value) {
			addCriterion("notiesms <=", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsLike(String value) {
			addCriterion("notiesms like", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsNotLike(String value) {
			addCriterion("notiesms not like", value, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsIn(List<String> values) {
			addCriterion("notiesms in", values, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsNotIn(List<String> values) {
			addCriterion("notiesms not in", values, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsBetween(String value1, String value2) {
			addCriterion("notiesms between", value1, value2, "notiesms");
			return (Criteria) this;
		}

		public Criteria andNotiesmsNotBetween(String value1, String value2) {
			addCriterion("notiesms not between", value1, value2, "notiesms");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddIsNull() {
			addCriterion("birthyyyymmdd is null");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddIsNotNull() {
			addCriterion("birthyyyymmdd is not null");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddEqualTo(String value) {
			addCriterion("birthyyyymmdd =", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddNotEqualTo(String value) {
			addCriterion("birthyyyymmdd <>", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddGreaterThan(String value) {
			addCriterion("birthyyyymmdd >", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddGreaterThanOrEqualTo(String value) {
			addCriterion("birthyyyymmdd >=", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddLessThan(String value) {
			addCriterion("birthyyyymmdd <", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddLessThanOrEqualTo(String value) {
			addCriterion("birthyyyymmdd <=", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddLike(String value) {
			addCriterion("birthyyyymmdd like", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddNotLike(String value) {
			addCriterion("birthyyyymmdd not like", value, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddIn(List<String> values) {
			addCriterion("birthyyyymmdd in", values, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddNotIn(List<String> values) {
			addCriterion("birthyyyymmdd not in", values, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddBetween(String value1, String value2) {
			addCriterion("birthyyyymmdd between", value1, value2, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andBirthyyyymmddNotBetween(String value1, String value2) {
			addCriterion("birthyyyymmdd not between", value1, value2, "birthyyyymmdd");
			return (Criteria) this;
		}

		public Criteria andTutortypeIsNull() {
			addCriterion("tutortype is null");
			return (Criteria) this;
		}

		public Criteria andTutortypeIsNotNull() {
			addCriterion("tutortype is not null");
			return (Criteria) this;
		}

		public Criteria andTutortypeEqualTo(String value) {
			addCriterion("tutortype =", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeNotEqualTo(String value) {
			addCriterion("tutortype <>", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeGreaterThan(String value) {
			addCriterion("tutortype >", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeGreaterThanOrEqualTo(String value) {
			addCriterion("tutortype >=", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeLessThan(String value) {
			addCriterion("tutortype <", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeLessThanOrEqualTo(String value) {
			addCriterion("tutortype <=", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeLike(String value) {
			addCriterion("tutortype like", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeNotLike(String value) {
			addCriterion("tutortype not like", value, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeIn(List<String> values) {
			addCriterion("tutortype in", values, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeNotIn(List<String> values) {
			addCriterion("tutortype not in", values, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeBetween(String value1, String value2) {
			addCriterion("tutortype between", value1, value2, "tutortype");
			return (Criteria) this;
		}

		public Criteria andTutortypeNotBetween(String value1, String value2) {
			addCriterion("tutortype not between", value1, value2, "tutortype");
			return (Criteria) this;
		}

		public Criteria andActiveareaIsNull() {
			addCriterion("activearea is null");
			return (Criteria) this;
		}

		public Criteria andActiveareaIsNotNull() {
			addCriterion("activearea is not null");
			return (Criteria) this;
		}

		public Criteria andActiveareaEqualTo(String value) {
			addCriterion("activearea =", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaNotEqualTo(String value) {
			addCriterion("activearea <>", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaGreaterThan(String value) {
			addCriterion("activearea >", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaGreaterThanOrEqualTo(String value) {
			addCriterion("activearea >=", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaLessThan(String value) {
			addCriterion("activearea <", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaLessThanOrEqualTo(String value) {
			addCriterion("activearea <=", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaLike(String value) {
			addCriterion("activearea like", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaNotLike(String value) {
			addCriterion("activearea not like", value, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaIn(List<String> values) {
			addCriterion("activearea in", values, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaNotIn(List<String> values) {
			addCriterion("activearea not in", values, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaBetween(String value1, String value2) {
			addCriterion("activearea between", value1, value2, "activearea");
			return (Criteria) this;
		}

		public Criteria andActiveareaNotBetween(String value1, String value2) {
			addCriterion("activearea not between", value1, value2, "activearea");
			return (Criteria) this;
		}

		public Criteria andAddrIsNull() {
			addCriterion("addr is null");
			return (Criteria) this;
		}

		public Criteria andAddrIsNotNull() {
			addCriterion("addr is not null");
			return (Criteria) this;
		}

		public Criteria andAddrEqualTo(String value) {
			addCriterion("addr =", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotEqualTo(String value) {
			addCriterion("addr <>", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThan(String value) {
			addCriterion("addr >", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThanOrEqualTo(String value) {
			addCriterion("addr >=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThan(String value) {
			addCriterion("addr <", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThanOrEqualTo(String value) {
			addCriterion("addr <=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLike(String value) {
			addCriterion("addr like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotLike(String value) {
			addCriterion("addr not like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrIn(List<String> values) {
			addCriterion("addr in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotIn(List<String> values) {
			addCriterion("addr not in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrBetween(String value1, String value2) {
			addCriterion("addr between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotBetween(String value1, String value2) {
			addCriterion("addr not between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andUsimgIsNull() {
			addCriterion("usimg is null");
			return (Criteria) this;
		}

		public Criteria andUsimgIsNotNull() {
			addCriterion("usimg is not null");
			return (Criteria) this;
		}

		public Criteria andUsimgEqualTo(String value) {
			addCriterion("usimg =", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgNotEqualTo(String value) {
			addCriterion("usimg <>", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgGreaterThan(String value) {
			addCriterion("usimg >", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgGreaterThanOrEqualTo(String value) {
			addCriterion("usimg >=", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgLessThan(String value) {
			addCriterion("usimg <", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgLessThanOrEqualTo(String value) {
			addCriterion("usimg <=", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgLike(String value) {
			addCriterion("usimg like", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgNotLike(String value) {
			addCriterion("usimg not like", value, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgIn(List<String> values) {
			addCriterion("usimg in", values, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgNotIn(List<String> values) {
			addCriterion("usimg not in", values, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgBetween(String value1, String value2) {
			addCriterion("usimg between", value1, value2, "usimg");
			return (Criteria) this;
		}

		public Criteria andUsimgNotBetween(String value1, String value2) {
			addCriterion("usimg not between", value1, value2, "usimg");
			return (Criteria) this;
		}

		public Criteria andMemo1IsNull() {
			addCriterion("memo1 is null");
			return (Criteria) this;
		}

		public Criteria andMemo1IsNotNull() {
			addCriterion("memo1 is not null");
			return (Criteria) this;
		}

		public Criteria andMemo1EqualTo(String value) {
			addCriterion("memo1 =", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1NotEqualTo(String value) {
			addCriterion("memo1 <>", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1GreaterThan(String value) {
			addCriterion("memo1 >", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1GreaterThanOrEqualTo(String value) {
			addCriterion("memo1 >=", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1LessThan(String value) {
			addCriterion("memo1 <", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1LessThanOrEqualTo(String value) {
			addCriterion("memo1 <=", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1Like(String value) {
			addCriterion("memo1 like", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1NotLike(String value) {
			addCriterion("memo1 not like", value, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1In(List<String> values) {
			addCriterion("memo1 in", values, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1NotIn(List<String> values) {
			addCriterion("memo1 not in", values, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1Between(String value1, String value2) {
			addCriterion("memo1 between", value1, value2, "memo1");
			return (Criteria) this;
		}

		public Criteria andMemo1NotBetween(String value1, String value2) {
			addCriterion("memo1 not between", value1, value2, "memo1");
			return (Criteria) this;
		}

		public Criteria andBankimgIsNull() {
			addCriterion("bankimg is null");
			return (Criteria) this;
		}

		public Criteria andBankimgIsNotNull() {
			addCriterion("bankimg is not null");
			return (Criteria) this;
		}

		public Criteria andBankimgEqualTo(String value) {
			addCriterion("bankimg =", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgNotEqualTo(String value) {
			addCriterion("bankimg <>", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgGreaterThan(String value) {
			addCriterion("bankimg >", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgGreaterThanOrEqualTo(String value) {
			addCriterion("bankimg >=", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgLessThan(String value) {
			addCriterion("bankimg <", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgLessThanOrEqualTo(String value) {
			addCriterion("bankimg <=", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgLike(String value) {
			addCriterion("bankimg like", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgNotLike(String value) {
			addCriterion("bankimg not like", value, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgIn(List<String> values) {
			addCriterion("bankimg in", values, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgNotIn(List<String> values) {
			addCriterion("bankimg not in", values, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgBetween(String value1, String value2) {
			addCriterion("bankimg between", value1, value2, "bankimg");
			return (Criteria) this;
		}

		public Criteria andBankimgNotBetween(String value1, String value2) {
			addCriterion("bankimg not between", value1, value2, "bankimg");
			return (Criteria) this;
		}

		public Criteria andRegimgIsNull() {
			addCriterion("regimg is null");
			return (Criteria) this;
		}

		public Criteria andRegimgIsNotNull() {
			addCriterion("regimg is not null");
			return (Criteria) this;
		}

		public Criteria andRegimgEqualTo(String value) {
			addCriterion("regimg =", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgNotEqualTo(String value) {
			addCriterion("regimg <>", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgGreaterThan(String value) {
			addCriterion("regimg >", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgGreaterThanOrEqualTo(String value) {
			addCriterion("regimg >=", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgLessThan(String value) {
			addCriterion("regimg <", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgLessThanOrEqualTo(String value) {
			addCriterion("regimg <=", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgLike(String value) {
			addCriterion("regimg like", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgNotLike(String value) {
			addCriterion("regimg not like", value, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgIn(List<String> values) {
			addCriterion("regimg in", values, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgNotIn(List<String> values) {
			addCriterion("regimg not in", values, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgBetween(String value1, String value2) {
			addCriterion("regimg between", value1, value2, "regimg");
			return (Criteria) this;
		}

		public Criteria andRegimgNotBetween(String value1, String value2) {
			addCriterion("regimg not between", value1, value2, "regimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgIsNull() {
			addCriterion("careerimg is null");
			return (Criteria) this;
		}

		public Criteria andCareerimgIsNotNull() {
			addCriterion("careerimg is not null");
			return (Criteria) this;
		}

		public Criteria andCareerimgEqualTo(String value) {
			addCriterion("careerimg =", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgNotEqualTo(String value) {
			addCriterion("careerimg <>", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgGreaterThan(String value) {
			addCriterion("careerimg >", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgGreaterThanOrEqualTo(String value) {
			addCriterion("careerimg >=", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgLessThan(String value) {
			addCriterion("careerimg <", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgLessThanOrEqualTo(String value) {
			addCriterion("careerimg <=", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgLike(String value) {
			addCriterion("careerimg like", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgNotLike(String value) {
			addCriterion("careerimg not like", value, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgIn(List<String> values) {
			addCriterion("careerimg in", values, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgNotIn(List<String> values) {
			addCriterion("careerimg not in", values, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgBetween(String value1, String value2) {
			addCriterion("careerimg between", value1, value2, "careerimg");
			return (Criteria) this;
		}

		public Criteria andCareerimgNotBetween(String value1, String value2) {
			addCriterion("careerimg not between", value1, value2, "careerimg");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1IsNull() {
			addCriterion("etcdocu1 is null");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1IsNotNull() {
			addCriterion("etcdocu1 is not null");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1EqualTo(String value) {
			addCriterion("etcdocu1 =", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1NotEqualTo(String value) {
			addCriterion("etcdocu1 <>", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1GreaterThan(String value) {
			addCriterion("etcdocu1 >", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1GreaterThanOrEqualTo(String value) {
			addCriterion("etcdocu1 >=", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1LessThan(String value) {
			addCriterion("etcdocu1 <", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1LessThanOrEqualTo(String value) {
			addCriterion("etcdocu1 <=", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1Like(String value) {
			addCriterion("etcdocu1 like", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1NotLike(String value) {
			addCriterion("etcdocu1 not like", value, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1In(List<String> values) {
			addCriterion("etcdocu1 in", values, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1NotIn(List<String> values) {
			addCriterion("etcdocu1 not in", values, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1Between(String value1, String value2) {
			addCriterion("etcdocu1 between", value1, value2, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu1NotBetween(String value1, String value2) {
			addCriterion("etcdocu1 not between", value1, value2, "etcdocu1");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2IsNull() {
			addCriterion("etcdocu2 is null");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2IsNotNull() {
			addCriterion("etcdocu2 is not null");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2EqualTo(String value) {
			addCriterion("etcdocu2 =", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2NotEqualTo(String value) {
			addCriterion("etcdocu2 <>", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2GreaterThan(String value) {
			addCriterion("etcdocu2 >", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2GreaterThanOrEqualTo(String value) {
			addCriterion("etcdocu2 >=", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2LessThan(String value) {
			addCriterion("etcdocu2 <", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2LessThanOrEqualTo(String value) {
			addCriterion("etcdocu2 <=", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2Like(String value) {
			addCriterion("etcdocu2 like", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2NotLike(String value) {
			addCriterion("etcdocu2 not like", value, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2In(List<String> values) {
			addCriterion("etcdocu2 in", values, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2NotIn(List<String> values) {
			addCriterion("etcdocu2 not in", values, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2Between(String value1, String value2) {
			addCriterion("etcdocu2 between", value1, value2, "etcdocu2");
			return (Criteria) this;
		}

		public Criteria andEtcdocu2NotBetween(String value1, String value2) {
			addCriterion("etcdocu2 not between", value1, value2, "etcdocu2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table usert
	 *
	 * @mbg.generated do_not_delete_during_merge Tue Dec 17 11:09:48 KST 2019
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table usert
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}