package com.ultarischool.usert;

public class vwctusdtt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.ctusdtlsn
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private Integer ctusdtlsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.tutorid
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String tutorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.kocode
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String kocode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.utjcode1
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String utjcode1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.utjcode2
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String utjcode2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.utjcode3
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String utjcode3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.username
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.email
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.mobile
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwctusdtt.activearea
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    private String activearea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.ctusdtlsn
     *
     * @return the value of vwctusdtt.ctusdtlsn
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public Integer getCtusdtlsn() {
        return ctusdtlsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.ctusdtlsn
     *
     * @param ctusdtlsn the value for vwctusdtt.ctusdtlsn
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setCtusdtlsn(Integer ctusdtlsn) {
        this.ctusdtlsn = ctusdtlsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.tutorid
     *
     * @return the value of vwctusdtt.tutorid
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getTutorid() {
        return tutorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.tutorid
     *
     * @param tutorid the value for vwctusdtt.tutorid
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setTutorid(String tutorid) {
        this.tutorid = tutorid == null ? null : tutorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.kocode
     *
     * @return the value of vwctusdtt.kocode
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getKocode() {
        return kocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.kocode
     *
     * @param kocode the value for vwctusdtt.kocode
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setKocode(String kocode) {
        this.kocode = kocode == null ? null : kocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.utjcode1
     *
     * @return the value of vwctusdtt.utjcode1
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getUtjcode1() {
        return utjcode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.utjcode1
     *
     * @param utjcode1 the value for vwctusdtt.utjcode1
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setUtjcode1(String utjcode1) {
        this.utjcode1 = utjcode1 == null ? null : utjcode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.utjcode2
     *
     * @return the value of vwctusdtt.utjcode2
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getUtjcode2() {
        return utjcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.utjcode2
     *
     * @param utjcode2 the value for vwctusdtt.utjcode2
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setUtjcode2(String utjcode2) {
        this.utjcode2 = utjcode2 == null ? null : utjcode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.utjcode3
     *
     * @return the value of vwctusdtt.utjcode3
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getUtjcode3() {
        return utjcode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.utjcode3
     *
     * @param utjcode3 the value for vwctusdtt.utjcode3
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setUtjcode3(String utjcode3) {
        this.utjcode3 = utjcode3 == null ? null : utjcode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.username
     *
     * @return the value of vwctusdtt.username
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.username
     *
     * @param username the value for vwctusdtt.username
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.email
     *
     * @return the value of vwctusdtt.email
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.email
     *
     * @param email the value for vwctusdtt.email
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.mobile
     *
     * @return the value of vwctusdtt.mobile
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.mobile
     *
     * @param mobile the value for vwctusdtt.mobile
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwctusdtt.activearea
     *
     * @return the value of vwctusdtt.activearea
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public String getActivearea() {
        return activearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwctusdtt.activearea
     *
     * @param activearea the value for vwctusdtt.activearea
     *
     * @mbg.generated Tue Jan 21 16:05:06 KST 2020
     */
    public void setActivearea(String activearea) {
        this.activearea = activearea == null ? null : activearea.trim();
    }
}