package com.ultarischool.utpafter;

public class utpafter {
    
	private String protitle = "";
	
	private String utj = "";
	public String getUtj() {
		return utj;
	}

	public void setUtj(String utj) {
		this.utj = utj;
	}

	public String getSch() {
		return sch;
	}

	public void setSch(String sch) {
		this.sch = sch;
	}

	public String getHak() {
		return hak;
	}

	public void setHak(String hak) {
		this.hak = hak;
	}

	public String getDdd() {
		return ddd;
	}

	public void setDdd(String ddd) {
		this.ddd = ddd;
	}

	private String sch = "";
	private String hak = "";
	private String ddd = "";
	
	public String getProtitle() {
		return protitle;
	}

	public void setProtitle(String protitle) {
		this.protitle = protitle;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpafter.sn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpafter.utpsn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    private Integer utpsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpafter.writer
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    private String writer;
    
    private String chasi;
    
    public String getChasi() {
		return chasi;
	}

	public void setChasi(String chasi) {
		this.chasi = chasi;
	}

	public String getNewchasi() {
		return newchasi;
	}

	public void setNewchasi(String newchasi) {
		this.newchasi = newchasi;
	}

	private String newchasi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpafter.cont
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    private String cont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpafter.wdate
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    private String wdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpafter.sn
     *
     * @return the value of utpafter.sn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpafter.sn
     *
     * @param sn the value for utpafter.sn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpafter.utpsn
     *
     * @return the value of utpafter.utpsn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public Integer getUtpsn() {
        return utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpafter.utpsn
     *
     * @param utpsn the value for utpafter.utpsn
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public void setUtpsn(Integer utpsn) {
        this.utpsn = utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpafter.writer
     *
     * @return the value of utpafter.writer
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpafter.writer
     *
     * @param writer the value for utpafter.writer
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpafter.cont
     *
     * @return the value of utpafter.cont
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpafter.cont
     *
     * @param cont the value for utpafter.cont
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public void setCont(String cont) {
        this.cont = cont == null ? null : cont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpafter.wdate
     *
     * @return the value of utpafter.wdate
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public String getWdate() {
        return wdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpafter.wdate
     *
     * @param wdate the value for utpafter.wdate
     *
     * @mbg.generated Mon Jan 13 14:48:19 KST 2020
     */
    public void setWdate(String wdate) {
        this.wdate = wdate == null ? null : wdate.trim();
    }
}