package com.ultarischool.hpbanner;

public class hpbanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.bnrtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bnrtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.img1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String img1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.img2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String img2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.info
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String memo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hpbanner.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String memo2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.sn
     *
     * @return the value of hpbanner.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.sn
     *
     * @param sn the value for hpbanner.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.bnrtype
     *
     * @return the value of hpbanner.bnrtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBnrtype() {
        return bnrtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.bnrtype
     *
     * @param bnrtype the value for hpbanner.bnrtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBnrtype(String bnrtype) {
        this.bnrtype = bnrtype == null ? null : bnrtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.img1
     *
     * @return the value of hpbanner.img1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.img1
     *
     * @param img1 the value for hpbanner.img1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.img2
     *
     * @return the value of hpbanner.img2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.img2
     *
     * @param img2 the value for hpbanner.img2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.title
     *
     * @return the value of hpbanner.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.title
     *
     * @param title the value for hpbanner.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.subtitle
     *
     * @return the value of hpbanner.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.subtitle
     *
     * @param subtitle the value for hpbanner.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.info
     *
     * @return the value of hpbanner.info
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.info
     *
     * @param info the value for hpbanner.info
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.memo1
     *
     * @return the value of hpbanner.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.memo1
     *
     * @param memo1 the value for hpbanner.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hpbanner.memo2
     *
     * @return the value of hpbanner.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hpbanner.memo2
     *
     * @param memo2 the value for hpbanner.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2 == null ? null : memo2.trim();
    }
}