package com.ultarischool.utprogramcha;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface utprogramchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(utprogramchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(utprogramchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(utprogramcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(utprogramcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    List<utprogramcha> selectByExample(utprogramchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    utprogramcha selectByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExampleSelective(@Param("record") utprogramcha record, @Param("example") utprogramchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") utprogramcha record, @Param("example") utprogramchaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(utprogramcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogramcha
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(utprogramcha record);
}