package com.ultarischool.bbs;

public class bbs {
    
	private String email;
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMemo2() {
		return memo2;
	}

	public void setMemo2(String memo2) {
		this.memo2 = memo2;
	}

	private String company;
	private String mobile;
	private String memo2;
	
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.userid
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.bbstype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bbstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String memo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.cnt
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer cnt;

    private String ansyn;
    public String getAnsyn() {
		return ansyn;
	}

	public void setAnsyn(String ansyn) {
		this.ansyn = ansyn;
	}

	private String afile1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.afile2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String afile2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.wdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String wdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.sn
     *
     * @return the value of bbs.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.sn
     *
     * @param sn the value for bbs.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.userid
     *
     * @return the value of bbs.userid
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.userid
     *
     * @param userid the value for bbs.userid
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.bbstype
     *
     * @return the value of bbs.bbstype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBbstype() {
        return bbstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.bbstype
     *
     * @param bbstype the value for bbs.bbstype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBbstype(String bbstype) {
        this.bbstype = bbstype == null ? null : bbstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.title
     *
     * @return the value of bbs.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.title
     *
     * @param title the value for bbs.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.memo1
     *
     * @return the value of bbs.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.memo1
     *
     * @param memo1 the value for bbs.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.cnt
     *
     * @return the value of bbs.cnt
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.cnt
     *
     * @param cnt the value for bbs.cnt
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.afile1
     *
     * @return the value of bbs.afile1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getAfile1() {
        return afile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.afile1
     *
     * @param afile1 the value for bbs.afile1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setAfile1(String afile1) {
        this.afile1 = afile1 == null ? null : afile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.afile2
     *
     * @return the value of bbs.afile2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getAfile2() {
        return afile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.afile2
     *
     * @param afile2 the value for bbs.afile2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setAfile2(String afile2) {
        this.afile2 = afile2 == null ? null : afile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.wdate
     *
     * @return the value of bbs.wdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getWdate() {
        return wdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.wdate
     *
     * @param wdate the value for bbs.wdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setWdate(String wdate) {
        this.wdate = wdate == null ? null : wdate.trim();
    }
}