package com.ultarischool.vwsvyresult;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class vwsvyresultExample extends PageVO {
	private Integer cosn;

	public Integer getCosn() {
		return cosn;
	}

	public void setCosn(Integer cosn) {
		this.cosn = cosn;
	}

	private String protitle = "";

	public String getProtitle() {
		return protitle;
	}

	public void setProtitle(String protitle) {
		this.protitle = protitle;
	}

	public String getElsname() {
		return elsname;
	}

	public void setElsname(String elsname) {
		this.elsname = elsname;
	}

	public String getSvname() {
		return svname;
	}

	public void setSvname(String svname) {
		this.svname = svname;
	}

	private String elsname = "";
	private String svname = "";

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public vwsvyresultExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSnIsNull() {
			addCriterion("sn is null");
			return (Criteria) this;
		}

		public Criteria andSnIsNotNull() {
			addCriterion("sn is not null");
			return (Criteria) this;
		}

		public Criteria andSnEqualTo(Integer value) {
			addCriterion("sn =", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotEqualTo(Integer value) {
			addCriterion("sn <>", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThan(Integer value) {
			addCriterion("sn >", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThanOrEqualTo(Integer value) {
			addCriterion("sn >=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThan(Integer value) {
			addCriterion("sn <", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThanOrEqualTo(Integer value) {
			addCriterion("sn <=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnIn(List<Integer> values) {
			addCriterion("sn in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotIn(List<Integer> values) {
			addCriterion("sn not in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnBetween(Integer value1, Integer value2) {
			addCriterion("sn between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotBetween(Integer value1, Integer value2) {
			addCriterion("sn not between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andOdrnoIsNull() {
			addCriterion("odrno is null");
			return (Criteria) this;
		}

		public Criteria andOdrnoIsNotNull() {
			addCriterion("odrno is not null");
			return (Criteria) this;
		}

		public Criteria andOdrnoEqualTo(String value) {
			addCriterion("odrno =", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoNotEqualTo(String value) {
			addCriterion("odrno <>", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoGreaterThan(String value) {
			addCriterion("odrno >", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoGreaterThanOrEqualTo(String value) {
			addCriterion("odrno >=", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoLessThan(String value) {
			addCriterion("odrno <", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoLessThanOrEqualTo(String value) {
			addCriterion("odrno <=", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoLike(String value) {
			addCriterion("odrno like", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoNotLike(String value) {
			addCriterion("odrno not like", value, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoIn(List<String> values) {
			addCriterion("odrno in", values, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoNotIn(List<String> values) {
			addCriterion("odrno not in", values, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoBetween(String value1, String value2) {
			addCriterion("odrno between", value1, value2, "odrno");
			return (Criteria) this;
		}

		public Criteria andOdrnoNotBetween(String value1, String value2) {
			addCriterion("odrno not between", value1, value2, "odrno");
			return (Criteria) this;
		}

		public Criteria andAnsIsNull() {
			addCriterion("ans is null");
			return (Criteria) this;
		}

		public Criteria andAnsIsNotNull() {
			addCriterion("ans is not null");
			return (Criteria) this;
		}

		public Criteria andAnsEqualTo(String value) {
			addCriterion("ans =", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsNotEqualTo(String value) {
			addCriterion("ans <>", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsGreaterThan(String value) {
			addCriterion("ans >", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsGreaterThanOrEqualTo(String value) {
			addCriterion("ans >=", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsLessThan(String value) {
			addCriterion("ans <", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsLessThanOrEqualTo(String value) {
			addCriterion("ans <=", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsLike(String value) {
			addCriterion("ans like", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsNotLike(String value) {
			addCriterion("ans not like", value, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsIn(List<String> values) {
			addCriterion("ans in", values, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsNotIn(List<String> values) {
			addCriterion("ans not in", values, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsBetween(String value1, String value2) {
			addCriterion("ans between", value1, value2, "ans");
			return (Criteria) this;
		}

		public Criteria andAnsNotBetween(String value1, String value2) {
			addCriterion("ans not between", value1, value2, "ans");
			return (Criteria) this;
		}

		public Criteria andSurveyfkIsNull() {
			addCriterion("surveyfk is null");
			return (Criteria) this;
		}

		public Criteria andSurveyfkIsNotNull() {
			addCriterion("surveyfk is not null");
			return (Criteria) this;
		}

		public Criteria andSurveyfkEqualTo(Integer value) {
			addCriterion("surveyfk =", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkNotEqualTo(Integer value) {
			addCriterion("surveyfk <>", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkGreaterThan(Integer value) {
			addCriterion("surveyfk >", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkGreaterThanOrEqualTo(Integer value) {
			addCriterion("surveyfk >=", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkLessThan(Integer value) {
			addCriterion("surveyfk <", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkLessThanOrEqualTo(Integer value) {
			addCriterion("surveyfk <=", value, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkIn(List<Integer> values) {
			addCriterion("surveyfk in", values, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkNotIn(List<Integer> values) {
			addCriterion("surveyfk not in", values, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkBetween(Integer value1, Integer value2) {
			addCriterion("surveyfk between", value1, value2, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andSurveyfkNotBetween(Integer value1, Integer value2) {
			addCriterion("surveyfk not between", value1, value2, "surveyfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNull() {
			addCriterion("useridfk is null");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNotNull() {
			addCriterion("useridfk is not null");
			return (Criteria) this;
		}

		public Criteria andUseridfkEqualTo(String value) {
			addCriterion("useridfk =", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotEqualTo(String value) {
			addCriterion("useridfk <>", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThan(String value) {
			addCriterion("useridfk >", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThanOrEqualTo(String value) {
			addCriterion("useridfk >=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThan(String value) {
			addCriterion("useridfk <", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThanOrEqualTo(String value) {
			addCriterion("useridfk <=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLike(String value) {
			addCriterion("useridfk like", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotLike(String value) {
			addCriterion("useridfk not like", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkIn(List<String> values) {
			addCriterion("useridfk in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotIn(List<String> values) {
			addCriterion("useridfk not in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkBetween(String value1, String value2) {
			addCriterion("useridfk between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotBetween(String value1, String value2) {
			addCriterion("useridfk not between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andClassnofkIsNull() {
			addCriterion("classnofk is null");
			return (Criteria) this;
		}

		public Criteria andClassnofkIsNotNull() {
			addCriterion("classnofk is not null");
			return (Criteria) this;
		}

		public Criteria andClassnofkEqualTo(Integer value) {
			addCriterion("classnofk =", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkNotEqualTo(Integer value) {
			addCriterion("classnofk <>", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkGreaterThan(Integer value) {
			addCriterion("classnofk >", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkGreaterThanOrEqualTo(Integer value) {
			addCriterion("classnofk >=", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkLessThan(Integer value) {
			addCriterion("classnofk <", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkLessThanOrEqualTo(Integer value) {
			addCriterion("classnofk <=", value, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkIn(List<Integer> values) {
			addCriterion("classnofk in", values, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkNotIn(List<Integer> values) {
			addCriterion("classnofk not in", values, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkBetween(Integer value1, Integer value2) {
			addCriterion("classnofk between", value1, value2, "classnofk");
			return (Criteria) this;
		}

		public Criteria andClassnofkNotBetween(Integer value1, Integer value2) {
			addCriterion("classnofk not between", value1, value2, "classnofk");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andBogi1IsNull() {
			addCriterion("bogi1 is null");
			return (Criteria) this;
		}

		public Criteria andBogi1IsNotNull() {
			addCriterion("bogi1 is not null");
			return (Criteria) this;
		}

		public Criteria andBogi1EqualTo(String value) {
			addCriterion("bogi1 =", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1NotEqualTo(String value) {
			addCriterion("bogi1 <>", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1GreaterThan(String value) {
			addCriterion("bogi1 >", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1GreaterThanOrEqualTo(String value) {
			addCriterion("bogi1 >=", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1LessThan(String value) {
			addCriterion("bogi1 <", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1LessThanOrEqualTo(String value) {
			addCriterion("bogi1 <=", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1Like(String value) {
			addCriterion("bogi1 like", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1NotLike(String value) {
			addCriterion("bogi1 not like", value, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1In(List<String> values) {
			addCriterion("bogi1 in", values, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1NotIn(List<String> values) {
			addCriterion("bogi1 not in", values, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1Between(String value1, String value2) {
			addCriterion("bogi1 between", value1, value2, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi1NotBetween(String value1, String value2) {
			addCriterion("bogi1 not between", value1, value2, "bogi1");
			return (Criteria) this;
		}

		public Criteria andBogi2IsNull() {
			addCriterion("bogi2 is null");
			return (Criteria) this;
		}

		public Criteria andBogi2IsNotNull() {
			addCriterion("bogi2 is not null");
			return (Criteria) this;
		}

		public Criteria andBogi2EqualTo(String value) {
			addCriterion("bogi2 =", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2NotEqualTo(String value) {
			addCriterion("bogi2 <>", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2GreaterThan(String value) {
			addCriterion("bogi2 >", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2GreaterThanOrEqualTo(String value) {
			addCriterion("bogi2 >=", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2LessThan(String value) {
			addCriterion("bogi2 <", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2LessThanOrEqualTo(String value) {
			addCriterion("bogi2 <=", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2Like(String value) {
			addCriterion("bogi2 like", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2NotLike(String value) {
			addCriterion("bogi2 not like", value, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2In(List<String> values) {
			addCriterion("bogi2 in", values, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2NotIn(List<String> values) {
			addCriterion("bogi2 not in", values, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2Between(String value1, String value2) {
			addCriterion("bogi2 between", value1, value2, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi2NotBetween(String value1, String value2) {
			addCriterion("bogi2 not between", value1, value2, "bogi2");
			return (Criteria) this;
		}

		public Criteria andBogi3IsNull() {
			addCriterion("bogi3 is null");
			return (Criteria) this;
		}

		public Criteria andBogi3IsNotNull() {
			addCriterion("bogi3 is not null");
			return (Criteria) this;
		}

		public Criteria andBogi3EqualTo(String value) {
			addCriterion("bogi3 =", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3NotEqualTo(String value) {
			addCriterion("bogi3 <>", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3GreaterThan(String value) {
			addCriterion("bogi3 >", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3GreaterThanOrEqualTo(String value) {
			addCriterion("bogi3 >=", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3LessThan(String value) {
			addCriterion("bogi3 <", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3LessThanOrEqualTo(String value) {
			addCriterion("bogi3 <=", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3Like(String value) {
			addCriterion("bogi3 like", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3NotLike(String value) {
			addCriterion("bogi3 not like", value, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3In(List<String> values) {
			addCriterion("bogi3 in", values, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3NotIn(List<String> values) {
			addCriterion("bogi3 not in", values, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3Between(String value1, String value2) {
			addCriterion("bogi3 between", value1, value2, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi3NotBetween(String value1, String value2) {
			addCriterion("bogi3 not between", value1, value2, "bogi3");
			return (Criteria) this;
		}

		public Criteria andBogi4IsNull() {
			addCriterion("bogi4 is null");
			return (Criteria) this;
		}

		public Criteria andBogi4IsNotNull() {
			addCriterion("bogi4 is not null");
			return (Criteria) this;
		}

		public Criteria andBogi4EqualTo(String value) {
			addCriterion("bogi4 =", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4NotEqualTo(String value) {
			addCriterion("bogi4 <>", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4GreaterThan(String value) {
			addCriterion("bogi4 >", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4GreaterThanOrEqualTo(String value) {
			addCriterion("bogi4 >=", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4LessThan(String value) {
			addCriterion("bogi4 <", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4LessThanOrEqualTo(String value) {
			addCriterion("bogi4 <=", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4Like(String value) {
			addCriterion("bogi4 like", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4NotLike(String value) {
			addCriterion("bogi4 not like", value, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4In(List<String> values) {
			addCriterion("bogi4 in", values, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4NotIn(List<String> values) {
			addCriterion("bogi4 not in", values, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4Between(String value1, String value2) {
			addCriterion("bogi4 between", value1, value2, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi4NotBetween(String value1, String value2) {
			addCriterion("bogi4 not between", value1, value2, "bogi4");
			return (Criteria) this;
		}

		public Criteria andBogi5IsNull() {
			addCriterion("bogi5 is null");
			return (Criteria) this;
		}

		public Criteria andBogi5IsNotNull() {
			addCriterion("bogi5 is not null");
			return (Criteria) this;
		}

		public Criteria andBogi5EqualTo(String value) {
			addCriterion("bogi5 =", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5NotEqualTo(String value) {
			addCriterion("bogi5 <>", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5GreaterThan(String value) {
			addCriterion("bogi5 >", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5GreaterThanOrEqualTo(String value) {
			addCriterion("bogi5 >=", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5LessThan(String value) {
			addCriterion("bogi5 <", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5LessThanOrEqualTo(String value) {
			addCriterion("bogi5 <=", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5Like(String value) {
			addCriterion("bogi5 like", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5NotLike(String value) {
			addCriterion("bogi5 not like", value, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5In(List<String> values) {
			addCriterion("bogi5 in", values, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5NotIn(List<String> values) {
			addCriterion("bogi5 not in", values, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5Between(String value1, String value2) {
			addCriterion("bogi5 between", value1, value2, "bogi5");
			return (Criteria) this;
		}

		public Criteria andBogi5NotBetween(String value1, String value2) {
			addCriterion("bogi5 not between", value1, value2, "bogi5");
			return (Criteria) this;
		}

		public Criteria andSvnameIsNull() {
			addCriterion("svname is null");
			return (Criteria) this;
		}

		public Criteria andSvnameIsNotNull() {
			addCriterion("svname is not null");
			return (Criteria) this;
		}

		public Criteria andSvnameEqualTo(String value) {
			addCriterion("svname =", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameNotEqualTo(String value) {
			addCriterion("svname <>", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameGreaterThan(String value) {
			addCriterion("svname >", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameGreaterThanOrEqualTo(String value) {
			addCriterion("svname >=", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameLessThan(String value) {
			addCriterion("svname <", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameLessThanOrEqualTo(String value) {
			addCriterion("svname <=", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameLike(String value) {
			addCriterion("svname like", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameNotLike(String value) {
			addCriterion("svname not like", value, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameIn(List<String> values) {
			addCriterion("svname in", values, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameNotIn(List<String> values) {
			addCriterion("svname not in", values, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameBetween(String value1, String value2) {
			addCriterion("svname between", value1, value2, "svname");
			return (Criteria) this;
		}

		public Criteria andSvnameNotBetween(String value1, String value2) {
			addCriterion("svname not between", value1, value2, "svname");
			return (Criteria) this;
		}

		public Criteria andStunameIsNull() {
			addCriterion("stuname is null");
			return (Criteria) this;
		}

		public Criteria andStunameIsNotNull() {
			addCriterion("stuname is not null");
			return (Criteria) this;
		}

		public Criteria andStunameEqualTo(String value) {
			addCriterion("stuname =", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameNotEqualTo(String value) {
			addCriterion("stuname <>", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameGreaterThan(String value) {
			addCriterion("stuname >", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameGreaterThanOrEqualTo(String value) {
			addCriterion("stuname >=", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameLessThan(String value) {
			addCriterion("stuname <", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameLessThanOrEqualTo(String value) {
			addCriterion("stuname <=", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameLike(String value) {
			addCriterion("stuname like", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameNotLike(String value) {
			addCriterion("stuname not like", value, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameIn(List<String> values) {
			addCriterion("stuname in", values, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameNotIn(List<String> values) {
			addCriterion("stuname not in", values, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameBetween(String value1, String value2) {
			addCriterion("stuname between", value1, value2, "stuname");
			return (Criteria) this;
		}

		public Criteria andStunameNotBetween(String value1, String value2) {
			addCriterion("stuname not between", value1, value2, "stuname");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userid like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userid not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andElsnameIsNull() {
			addCriterion("elsname is null");
			return (Criteria) this;
		}

		public Criteria andElsnameIsNotNull() {
			addCriterion("elsname is not null");
			return (Criteria) this;
		}

		public Criteria andElsnameEqualTo(String value) {
			addCriterion("elsname =", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameNotEqualTo(String value) {
			addCriterion("elsname <>", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameGreaterThan(String value) {
			addCriterion("elsname >", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameGreaterThanOrEqualTo(String value) {
			addCriterion("elsname >=", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameLessThan(String value) {
			addCriterion("elsname <", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameLessThanOrEqualTo(String value) {
			addCriterion("elsname <=", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameLike(String value) {
			addCriterion("elsname like", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameNotLike(String value) {
			addCriterion("elsname not like", value, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameIn(List<String> values) {
			addCriterion("elsname in", values, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameNotIn(List<String> values) {
			addCriterion("elsname not in", values, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameBetween(String value1, String value2) {
			addCriterion("elsname between", value1, value2, "elsname");
			return (Criteria) this;
		}

		public Criteria andElsnameNotBetween(String value1, String value2) {
			addCriterion("elsname not between", value1, value2, "elsname");
			return (Criteria) this;
		}

		public Criteria andTutoridIsNull() {
			addCriterion("tutorid is null");
			return (Criteria) this;
		}

		public Criteria andTutoridIsNotNull() {
			addCriterion("tutorid is not null");
			return (Criteria) this;
		}

		public Criteria andTutoridEqualTo(String value) {
			addCriterion("tutorid =", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridNotEqualTo(String value) {
			addCriterion("tutorid <>", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridGreaterThan(String value) {
			addCriterion("tutorid >", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridGreaterThanOrEqualTo(String value) {
			addCriterion("tutorid >=", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridLessThan(String value) {
			addCriterion("tutorid <", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridLessThanOrEqualTo(String value) {
			addCriterion("tutorid <=", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridLike(String value) {
			addCriterion("tutorid like", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridNotLike(String value) {
			addCriterion("tutorid not like", value, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridIn(List<String> values) {
			addCriterion("tutorid in", values, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridNotIn(List<String> values) {
			addCriterion("tutorid not in", values, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridBetween(String value1, String value2) {
			addCriterion("tutorid between", value1, value2, "tutorid");
			return (Criteria) this;
		}

		public Criteria andTutoridNotBetween(String value1, String value2) {
			addCriterion("tutorid not between", value1, value2, "tutorid");
			return (Criteria) this;
		}

		public Criteria andStimeIsNull() {
			addCriterion("stime is null");
			return (Criteria) this;
		}

		public Criteria andStimeIsNotNull() {
			addCriterion("stime is not null");
			return (Criteria) this;
		}

		public Criteria andStimeEqualTo(String value) {
			addCriterion("stime =", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotEqualTo(String value) {
			addCriterion("stime <>", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeGreaterThan(String value) {
			addCriterion("stime >", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeGreaterThanOrEqualTo(String value) {
			addCriterion("stime >=", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLessThan(String value) {
			addCriterion("stime <", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLessThanOrEqualTo(String value) {
			addCriterion("stime <=", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLike(String value) {
			addCriterion("stime like", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotLike(String value) {
			addCriterion("stime not like", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeIn(List<String> values) {
			addCriterion("stime in", values, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotIn(List<String> values) {
			addCriterion("stime not in", values, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeBetween(String value1, String value2) {
			addCriterion("stime between", value1, value2, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotBetween(String value1, String value2) {
			addCriterion("stime not between", value1, value2, "stime");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNull() {
			addCriterion("etime is null");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNotNull() {
			addCriterion("etime is not null");
			return (Criteria) this;
		}

		public Criteria andEtimeEqualTo(String value) {
			addCriterion("etime =", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotEqualTo(String value) {
			addCriterion("etime <>", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThan(String value) {
			addCriterion("etime >", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThanOrEqualTo(String value) {
			addCriterion("etime >=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThan(String value) {
			addCriterion("etime <", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThanOrEqualTo(String value) {
			addCriterion("etime <=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLike(String value) {
			addCriterion("etime like", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotLike(String value) {
			addCriterion("etime not like", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeIn(List<String> values) {
			addCriterion("etime in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotIn(List<String> values) {
			addCriterion("etime not in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeBetween(String value1, String value2) {
			addCriterion("etime between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotBetween(String value1, String value2) {
			addCriterion("etime not between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andKojobcodeIsNull() {
			addCriterion("kojobcode is null");
			return (Criteria) this;
		}

		public Criteria andKojobcodeIsNotNull() {
			addCriterion("kojobcode is not null");
			return (Criteria) this;
		}

		public Criteria andKojobcodeEqualTo(String value) {
			addCriterion("kojobcode =", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeNotEqualTo(String value) {
			addCriterion("kojobcode <>", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeGreaterThan(String value) {
			addCriterion("kojobcode >", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeGreaterThanOrEqualTo(String value) {
			addCriterion("kojobcode >=", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeLessThan(String value) {
			addCriterion("kojobcode <", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeLessThanOrEqualTo(String value) {
			addCriterion("kojobcode <=", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeLike(String value) {
			addCriterion("kojobcode like", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeNotLike(String value) {
			addCriterion("kojobcode not like", value, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeIn(List<String> values) {
			addCriterion("kojobcode in", values, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeNotIn(List<String> values) {
			addCriterion("kojobcode not in", values, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeBetween(String value1, String value2) {
			addCriterion("kojobcode between", value1, value2, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andKojobcodeNotBetween(String value1, String value2) {
			addCriterion("kojobcode not between", value1, value2, "kojobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeIsNull() {
			addCriterion("utjobcode is null");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeIsNotNull() {
			addCriterion("utjobcode is not null");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeEqualTo(String value) {
			addCriterion("utjobcode =", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeNotEqualTo(String value) {
			addCriterion("utjobcode <>", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeGreaterThan(String value) {
			addCriterion("utjobcode >", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeGreaterThanOrEqualTo(String value) {
			addCriterion("utjobcode >=", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeLessThan(String value) {
			addCriterion("utjobcode <", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeLessThanOrEqualTo(String value) {
			addCriterion("utjobcode <=", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeLike(String value) {
			addCriterion("utjobcode like", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeNotLike(String value) {
			addCriterion("utjobcode not like", value, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeIn(List<String> values) {
			addCriterion("utjobcode in", values, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeNotIn(List<String> values) {
			addCriterion("utjobcode not in", values, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeBetween(String value1, String value2) {
			addCriterion("utjobcode between", value1, value2, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andUtjobcodeNotBetween(String value1, String value2) {
			addCriterion("utjobcode not between", value1, value2, "utjobcode");
			return (Criteria) this;
		}

		public Criteria andCallernameIsNull() {
			addCriterion("callername is null");
			return (Criteria) this;
		}

		public Criteria andCallernameIsNotNull() {
			addCriterion("callername is not null");
			return (Criteria) this;
		}

		public Criteria andCallernameEqualTo(String value) {
			addCriterion("callername =", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameNotEqualTo(String value) {
			addCriterion("callername <>", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameGreaterThan(String value) {
			addCriterion("callername >", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameGreaterThanOrEqualTo(String value) {
			addCriterion("callername >=", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameLessThan(String value) {
			addCriterion("callername <", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameLessThanOrEqualTo(String value) {
			addCriterion("callername <=", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameLike(String value) {
			addCriterion("callername like", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameNotLike(String value) {
			addCriterion("callername not like", value, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameIn(List<String> values) {
			addCriterion("callername in", values, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameNotIn(List<String> values) {
			addCriterion("callername not in", values, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameBetween(String value1, String value2) {
			addCriterion("callername between", value1, value2, "callername");
			return (Criteria) this;
		}

		public Criteria andCallernameNotBetween(String value1, String value2) {
			addCriterion("callername not between", value1, value2, "callername");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andSchclassIsNull() {
			addCriterion("schclass is null");
			return (Criteria) this;
		}

		public Criteria andSchclassIsNotNull() {
			addCriterion("schclass is not null");
			return (Criteria) this;
		}

		public Criteria andSchclassEqualTo(Integer value) {
			addCriterion("schclass =", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassNotEqualTo(Integer value) {
			addCriterion("schclass <>", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassGreaterThan(Integer value) {
			addCriterion("schclass >", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassGreaterThanOrEqualTo(Integer value) {
			addCriterion("schclass >=", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassLessThan(Integer value) {
			addCriterion("schclass <", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassLessThanOrEqualTo(Integer value) {
			addCriterion("schclass <=", value, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassIn(List<Integer> values) {
			addCriterion("schclass in", values, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassNotIn(List<Integer> values) {
			addCriterion("schclass not in", values, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassBetween(Integer value1, Integer value2) {
			addCriterion("schclass between", value1, value2, "schclass");
			return (Criteria) this;
		}

		public Criteria andSchclassNotBetween(Integer value1, Integer value2) {
			addCriterion("schclass not between", value1, value2, "schclass");
			return (Criteria) this;
		}

		public Criteria andUtpsnIsNull() {
			addCriterion("utpsn is null");
			return (Criteria) this;
		}

		public Criteria andUtpsnIsNotNull() {
			addCriterion("utpsn is not null");
			return (Criteria) this;
		}

		public Criteria andUtpsnEqualTo(Integer value) {
			addCriterion("utpsn =", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnNotEqualTo(Integer value) {
			addCriterion("utpsn <>", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnGreaterThan(Integer value) {
			addCriterion("utpsn >", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnGreaterThanOrEqualTo(Integer value) {
			addCriterion("utpsn >=", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnLessThan(Integer value) {
			addCriterion("utpsn <", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnLessThanOrEqualTo(Integer value) {
			addCriterion("utpsn <=", value, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnIn(List<Integer> values) {
			addCriterion("utpsn in", values, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnNotIn(List<Integer> values) {
			addCriterion("utpsn not in", values, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnBetween(Integer value1, Integer value2) {
			addCriterion("utpsn between", value1, value2, "utpsn");
			return (Criteria) this;
		}

		public Criteria andUtpsnNotBetween(Integer value1, Integer value2) {
			addCriterion("utpsn not between", value1, value2, "utpsn");
			return (Criteria) this;
		}

		public Criteria andProtitleIsNull() {
			addCriterion("protitle is null");
			return (Criteria) this;
		}

		public Criteria andProtitleIsNotNull() {
			addCriterion("protitle is not null");
			return (Criteria) this;
		}

		public Criteria andProtitleEqualTo(String value) {
			addCriterion("protitle =", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleNotEqualTo(String value) {
			addCriterion("protitle <>", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleGreaterThan(String value) {
			addCriterion("protitle >", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleGreaterThanOrEqualTo(String value) {
			addCriterion("protitle >=", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleLessThan(String value) {
			addCriterion("protitle <", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleLessThanOrEqualTo(String value) {
			addCriterion("protitle <=", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleLike(String value) {
			addCriterion("protitle like", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleNotLike(String value) {
			addCriterion("protitle not like", value, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleIn(List<String> values) {
			addCriterion("protitle in", values, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleNotIn(List<String> values) {
			addCriterion("protitle not in", values, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleBetween(String value1, String value2) {
			addCriterion("protitle between", value1, value2, "protitle");
			return (Criteria) this;
		}

		public Criteria andProtitleNotBetween(String value1, String value2) {
			addCriterion("protitle not between", value1, value2, "protitle");
			return (Criteria) this;
		}

		public Criteria andTutornameIsNull() {
			addCriterion("tutorname is null");
			return (Criteria) this;
		}

		public Criteria andTutornameIsNotNull() {
			addCriterion("tutorname is not null");
			return (Criteria) this;
		}

		public Criteria andTutornameEqualTo(String value) {
			addCriterion("tutorname =", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameNotEqualTo(String value) {
			addCriterion("tutorname <>", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameGreaterThan(String value) {
			addCriterion("tutorname >", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameGreaterThanOrEqualTo(String value) {
			addCriterion("tutorname >=", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameLessThan(String value) {
			addCriterion("tutorname <", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameLessThanOrEqualTo(String value) {
			addCriterion("tutorname <=", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameLike(String value) {
			addCriterion("tutorname like", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameNotLike(String value) {
			addCriterion("tutorname not like", value, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameIn(List<String> values) {
			addCriterion("tutorname in", values, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameNotIn(List<String> values) {
			addCriterion("tutorname not in", values, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameBetween(String value1, String value2) {
			addCriterion("tutorname between", value1, value2, "tutorname");
			return (Criteria) this;
		}

		public Criteria andTutornameNotBetween(String value1, String value2) {
			addCriterion("tutorname not between", value1, value2, "tutorname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated do_not_delete_during_merge Mon Jan 20 11:22:29 KST 2020
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table vwsvyresult
	 *
	 * @mbg.generated Mon Jan 20 11:22:29 KST 2020
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}