package com.ultarischool.vwsvyresult;

public class vwsvyresult {
	
	
	private String totalbogi;
	
	private String type1;
	
	
	public String getType1() {
		return type1;
	}

	public void setType1(String type1) {
		this.type1 = type1;
	}

	public String getTotalbogi() {
		return totalbogi;
	}

	public void setTotalbogi(String totalbogi) {
		this.totalbogi = totalbogi;
	}

	public String getPer1() {
		return per1;
	}

	public void setPer1(String per1) {
		this.per1 = per1;
	}

	public String getPer2() {
		return per2;
	}

	public void setPer2(String per2) {
		this.per2 = per2;
	}

	public String getPer3() {
		return per3;
	}

	public void setPer3(String per3) {
		this.per3 = per3;
	}

	public String getPer4() {
		return per4;
	}

	public void setPer4(String per4) {
		this.per4 = per4;
	}

	public String getPer5() {
		return per5;
	}

	public void setPer5(String per5) {
		this.per5 = per5;
	}

	private String per1;
	private String per2;
	private String per3;
	private String per4;
	private String per5;
	
	
	
	private String bogi1t;
	public String getBogi1t() {
		return bogi1t;
	}

	public void setBogi1t(String bogi1t) {
		this.bogi1t = bogi1t;
	}

	public String getBogi2t() {
		return bogi2t;
	}

	public void setBogi2t(String bogi2t) {
		this.bogi2t = bogi2t;
	}

	public String getBogi3t() {
		return bogi3t;
	}

	public void setBogi3t(String bogi3t) {
		this.bogi3t = bogi3t;
	}

	public String getBogi4t() {
		return bogi4t;
	}

	public void setBogi4t(String bogi4t) {
		this.bogi4t = bogi4t;
	}

	public String getBogi5t() {
		return bogi5t;
	}

	public void setBogi5t(String bogi5t) {
		this.bogi5t = bogi5t;
	}

	private String bogi2t;
	private String bogi3t;
	private String bogi4t;
	private String bogi5t;
	
	
	private String spcnt;
	
	public String getSpcnt() {
		return spcnt;
	}

	public void setSpcnt(String spcnt) {
		this.spcnt = spcnt;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.sn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.odrno
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String odrno;
    
    private String usban;
    
    private String dday;


    public String getDday() {
		return dday;
	}

	public void setDday(String dday) {
		this.dday = dday;
	}

	public String getUsban() {
		return usban;
	}

	public void setUsban(String usban) {
		this.usban = usban;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.ans
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String ans;
    
    public String getUsyear() {
		return usyear;
	}

	public void setUsyear(String usyear) {
		this.usyear = usyear;
	}

	private String usyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.surveyfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private Integer surveyfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.useridfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String useridfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.classnofk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private Integer classnofk;
    
    private Integer cosn;

    public Integer getCosn() {
		return cosn;
	}

	public void setCosn(Integer cosn) {
		this.cosn = cosn;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.title
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.bogi1
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String bogi1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.bogi2
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String bogi2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.bogi3
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String bogi3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.bogi4
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String bogi4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.bogi5
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String bogi5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.svname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String svname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.stuname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.userid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.elsname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String elsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.tutorid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String tutorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.stime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.etime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.kojobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String kojobcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.utjobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String utjobcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.callername
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String callername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.email
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.schclass
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private Integer schclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.utpsn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private Integer utpsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.protitle
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String protitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwsvyresult.tutorname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    private String tutorname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.sn
     *
     * @return the value of vwsvyresult.sn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.sn
     *
     * @param sn the value for vwsvyresult.sn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.odrno
     *
     * @return the value of vwsvyresult.odrno
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getOdrno() {
        return odrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.odrno
     *
     * @param odrno the value for vwsvyresult.odrno
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setOdrno(String odrno) {
        this.odrno = odrno == null ? null : odrno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.ans
     *
     * @return the value of vwsvyresult.ans
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getAns() {
        return ans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.ans
     *
     * @param ans the value for vwsvyresult.ans
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setAns(String ans) {
        this.ans = ans == null ? null : ans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.surveyfk
     *
     * @return the value of vwsvyresult.surveyfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public Integer getSurveyfk() {
        return surveyfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.surveyfk
     *
     * @param surveyfk the value for vwsvyresult.surveyfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setSurveyfk(Integer surveyfk) {
        this.surveyfk = surveyfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.useridfk
     *
     * @return the value of vwsvyresult.useridfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getUseridfk() {
        return useridfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.useridfk
     *
     * @param useridfk the value for vwsvyresult.useridfk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setUseridfk(String useridfk) {
        this.useridfk = useridfk == null ? null : useridfk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.classnofk
     *
     * @return the value of vwsvyresult.classnofk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public Integer getClassnofk() {
        return classnofk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.classnofk
     *
     * @param classnofk the value for vwsvyresult.classnofk
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setClassnofk(Integer classnofk) {
        this.classnofk = classnofk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.title
     *
     * @return the value of vwsvyresult.title
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.title
     *
     * @param title the value for vwsvyresult.title
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.bogi1
     *
     * @return the value of vwsvyresult.bogi1
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getBogi1() {
        return bogi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.bogi1
     *
     * @param bogi1 the value for vwsvyresult.bogi1
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setBogi1(String bogi1) {
        this.bogi1 = bogi1 == null ? null : bogi1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.bogi2
     *
     * @return the value of vwsvyresult.bogi2
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getBogi2() {
        return bogi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.bogi2
     *
     * @param bogi2 the value for vwsvyresult.bogi2
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setBogi2(String bogi2) {
        this.bogi2 = bogi2 == null ? null : bogi2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.bogi3
     *
     * @return the value of vwsvyresult.bogi3
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getBogi3() {
        return bogi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.bogi3
     *
     * @param bogi3 the value for vwsvyresult.bogi3
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setBogi3(String bogi3) {
        this.bogi3 = bogi3 == null ? null : bogi3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.bogi4
     *
     * @return the value of vwsvyresult.bogi4
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getBogi4() {
        return bogi4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.bogi4
     *
     * @param bogi4 the value for vwsvyresult.bogi4
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setBogi4(String bogi4) {
        this.bogi4 = bogi4 == null ? null : bogi4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.bogi5
     *
     * @return the value of vwsvyresult.bogi5
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getBogi5() {
        return bogi5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.bogi5
     *
     * @param bogi5 the value for vwsvyresult.bogi5
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setBogi5(String bogi5) {
        this.bogi5 = bogi5 == null ? null : bogi5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.svname
     *
     * @return the value of vwsvyresult.svname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getSvname() {
        return svname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.svname
     *
     * @param svname the value for vwsvyresult.svname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setSvname(String svname) {
        this.svname = svname == null ? null : svname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.stuname
     *
     * @return the value of vwsvyresult.stuname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.stuname
     *
     * @param stuname the value for vwsvyresult.stuname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.userid
     *
     * @return the value of vwsvyresult.userid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.userid
     *
     * @param userid the value for vwsvyresult.userid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.elsname
     *
     * @return the value of vwsvyresult.elsname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getElsname() {
        return elsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.elsname
     *
     * @param elsname the value for vwsvyresult.elsname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setElsname(String elsname) {
        this.elsname = elsname == null ? null : elsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.tutorid
     *
     * @return the value of vwsvyresult.tutorid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getTutorid() {
        return tutorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.tutorid
     *
     * @param tutorid the value for vwsvyresult.tutorid
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setTutorid(String tutorid) {
        this.tutorid = tutorid == null ? null : tutorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.stime
     *
     * @return the value of vwsvyresult.stime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.stime
     *
     * @param stime the value for vwsvyresult.stime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setStime(String stime) {
        this.stime = stime == null ? null : stime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.etime
     *
     * @return the value of vwsvyresult.etime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.etime
     *
     * @param etime the value for vwsvyresult.etime
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setEtime(String etime) {
        this.etime = etime == null ? null : etime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.kojobcode
     *
     * @return the value of vwsvyresult.kojobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getKojobcode() {
        return kojobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.kojobcode
     *
     * @param kojobcode the value for vwsvyresult.kojobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setKojobcode(String kojobcode) {
        this.kojobcode = kojobcode == null ? null : kojobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.utjobcode
     *
     * @return the value of vwsvyresult.utjobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getUtjobcode() {
        return utjobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.utjobcode
     *
     * @param utjobcode the value for vwsvyresult.utjobcode
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setUtjobcode(String utjobcode) {
        this.utjobcode = utjobcode == null ? null : utjobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.callername
     *
     * @return the value of vwsvyresult.callername
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getCallername() {
        return callername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.callername
     *
     * @param callername the value for vwsvyresult.callername
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setCallername(String callername) {
        this.callername = callername == null ? null : callername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.email
     *
     * @return the value of vwsvyresult.email
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.email
     *
     * @param email the value for vwsvyresult.email
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.schclass
     *
     * @return the value of vwsvyresult.schclass
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public Integer getSchclass() {
        return schclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.schclass
     *
     * @param schclass the value for vwsvyresult.schclass
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setSchclass(Integer schclass) {
        this.schclass = schclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.utpsn
     *
     * @return the value of vwsvyresult.utpsn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public Integer getUtpsn() {
        return utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.utpsn
     *
     * @param utpsn the value for vwsvyresult.utpsn
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setUtpsn(Integer utpsn) {
        this.utpsn = utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.protitle
     *
     * @return the value of vwsvyresult.protitle
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getProtitle() {
        return protitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.protitle
     *
     * @param protitle the value for vwsvyresult.protitle
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setProtitle(String protitle) {
        this.protitle = protitle == null ? null : protitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwsvyresult.tutorname
     *
     * @return the value of vwsvyresult.tutorname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public String getTutorname() {
        return tutorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwsvyresult.tutorname
     *
     * @param tutorname the value for vwsvyresult.tutorname
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    public void setTutorname(String tutorname) {
        this.tutorname = tutorname == null ? null : tutorname.trim();
    }
}