package com.ultarischool.vwsvyresult;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ultarischool.vwsvyresult.vwsvyresult;
import com.ultarischool.vwsvyresult.vwsvyresultExample;

public interface vwsvyresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int countByExample(vwsvyresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int deleteByExample(vwsvyresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int insert(vwsvyresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int insertSelective(vwsvyresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    List<vwsvyresult> selectByExample(vwsvyresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int updateByExampleSelective(@Param("record") vwsvyresult record, @Param("example") vwsvyresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwsvyresult
     *
     * @mbg.generated Mon Jan 20 11:22:29 KST 2020
     */
    int updateByExample(@Param("record") vwsvyresult record, @Param("example") vwsvyresultExample example);
}