package com.ultarischool.vwtableinfo;

public class vwtableinfoWithBLOBs extends vwtableinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwtableinfo.columntype
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    private String columntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwtableinfo.columndefault
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    private String columndefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwtableinfo.columntype
     *
     * @return the value of vwtableinfo.columntype
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public String getColumntype() {
        return columntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwtableinfo.columntype
     *
     * @param columntype the value for vwtableinfo.columntype
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void setColumntype(String columntype) {
        this.columntype = columntype == null ? null : columntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwtableinfo.columndefault
     *
     * @return the value of vwtableinfo.columndefault
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public String getColumndefault() {
        return columndefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vwtableinfo.columndefault
     *
     * @param columndefault the value for vwtableinfo.columndefault
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void setColumndefault(String columndefault) {
        this.columndefault = columndefault == null ? null : columndefault.trim();
    }
}