package com.ultarischool.vwtableinfo;

import java.util.ArrayList;
import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import edumgt.common.util.PageVO;

public class vwtableinfoExample extends  PageVO{
	
	
    
	private String tablename = "";
	
	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public vwtableinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTablenameIsNull() {
            addCriterion("tablename is null");
            return (Criteria) this;
        }

        public Criteria andTablenameIsNotNull() {
            addCriterion("tablename is not null");
            return (Criteria) this;
        }

        public Criteria andTablenameEqualTo(String value) {
            addCriterion("tablename =", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotEqualTo(String value) {
            addCriterion("tablename <>", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThan(String value) {
            addCriterion("tablename >", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameGreaterThanOrEqualTo(String value) {
            addCriterion("tablename >=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThan(String value) {
            addCriterion("tablename <", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLessThanOrEqualTo(String value) {
            addCriterion("tablename <=", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameLike(String value) {
            addCriterion("tablename like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotLike(String value) {
            addCriterion("tablename not like", value, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameIn(List<String> values) {
            addCriterion("tablename in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotIn(List<String> values) {
            addCriterion("tablename not in", values, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameBetween(String value1, String value2) {
            addCriterion("tablename between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablenameNotBetween(String value1, String value2) {
            addCriterion("tablename not between", value1, value2, "tablename");
            return (Criteria) this;
        }

        public Criteria andTablecommentIsNull() {
            addCriterion("tablecomment is null");
            return (Criteria) this;
        }

        public Criteria andTablecommentIsNotNull() {
            addCriterion("tablecomment is not null");
            return (Criteria) this;
        }

        public Criteria andTablecommentEqualTo(String value) {
            addCriterion("tablecomment =", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentNotEqualTo(String value) {
            addCriterion("tablecomment <>", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentGreaterThan(String value) {
            addCriterion("tablecomment >", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentGreaterThanOrEqualTo(String value) {
            addCriterion("tablecomment >=", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentLessThan(String value) {
            addCriterion("tablecomment <", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentLessThanOrEqualTo(String value) {
            addCriterion("tablecomment <=", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentLike(String value) {
            addCriterion("tablecomment like", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentNotLike(String value) {
            addCriterion("tablecomment not like", value, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentIn(List<String> values) {
            addCriterion("tablecomment in", values, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentNotIn(List<String> values) {
            addCriterion("tablecomment not in", values, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentBetween(String value1, String value2) {
            addCriterion("tablecomment between", value1, value2, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andTablecommentNotBetween(String value1, String value2) {
            addCriterion("tablecomment not between", value1, value2, "tablecomment");
            return (Criteria) this;
        }

        public Criteria andColumnnameIsNull() {
            addCriterion("columnname is null");
            return (Criteria) this;
        }

        public Criteria andColumnnameIsNotNull() {
            addCriterion("columnname is not null");
            return (Criteria) this;
        }

        public Criteria andColumnnameEqualTo(String value) {
            addCriterion("columnname =", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameNotEqualTo(String value) {
            addCriterion("columnname <>", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameGreaterThan(String value) {
            addCriterion("columnname >", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameGreaterThanOrEqualTo(String value) {
            addCriterion("columnname >=", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameLessThan(String value) {
            addCriterion("columnname <", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameLessThanOrEqualTo(String value) {
            addCriterion("columnname <=", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameLike(String value) {
            addCriterion("columnname like", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameNotLike(String value) {
            addCriterion("columnname not like", value, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameIn(List<String> values) {
            addCriterion("columnname in", values, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameNotIn(List<String> values) {
            addCriterion("columnname not in", values, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameBetween(String value1, String value2) {
            addCriterion("columnname between", value1, value2, "columnname");
            return (Criteria) this;
        }

        public Criteria andColumnnameNotBetween(String value1, String value2) {
            addCriterion("columnname not between", value1, value2, "columnname");
            return (Criteria) this;
        }

        public Criteria andDatatypeIsNull() {
            addCriterion("datatype is null");
            return (Criteria) this;
        }

        public Criteria andDatatypeIsNotNull() {
            addCriterion("datatype is not null");
            return (Criteria) this;
        }

        public Criteria andDatatypeEqualTo(String value) {
            addCriterion("datatype =", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotEqualTo(String value) {
            addCriterion("datatype <>", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeGreaterThan(String value) {
            addCriterion("datatype >", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeGreaterThanOrEqualTo(String value) {
            addCriterion("datatype >=", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLessThan(String value) {
            addCriterion("datatype <", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLessThanOrEqualTo(String value) {
            addCriterion("datatype <=", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLike(String value) {
            addCriterion("datatype like", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotLike(String value) {
            addCriterion("datatype not like", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeIn(List<String> values) {
            addCriterion("datatype in", values, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotIn(List<String> values) {
            addCriterion("datatype not in", values, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeBetween(String value1, String value2) {
            addCriterion("datatype between", value1, value2, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotBetween(String value1, String value2) {
            addCriterion("datatype not between", value1, value2, "datatype");
            return (Criteria) this;
        }

        public Criteria andColumnkeyIsNull() {
            addCriterion("columnkey is null");
            return (Criteria) this;
        }

        public Criteria andColumnkeyIsNotNull() {
            addCriterion("columnkey is not null");
            return (Criteria) this;
        }

        public Criteria andColumnkeyEqualTo(String value) {
            addCriterion("columnkey =", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyNotEqualTo(String value) {
            addCriterion("columnkey <>", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyGreaterThan(String value) {
            addCriterion("columnkey >", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyGreaterThanOrEqualTo(String value) {
            addCriterion("columnkey >=", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyLessThan(String value) {
            addCriterion("columnkey <", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyLessThanOrEqualTo(String value) {
            addCriterion("columnkey <=", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyLike(String value) {
            addCriterion("columnkey like", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyNotLike(String value) {
            addCriterion("columnkey not like", value, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyIn(List<String> values) {
            addCriterion("columnkey in", values, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyNotIn(List<String> values) {
            addCriterion("columnkey not in", values, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyBetween(String value1, String value2) {
            addCriterion("columnkey between", value1, value2, "columnkey");
            return (Criteria) this;
        }

        public Criteria andColumnkeyNotBetween(String value1, String value2) {
            addCriterion("columnkey not between", value1, value2, "columnkey");
            return (Criteria) this;
        }

        public Criteria andIsnullableIsNull() {
            addCriterion("isnullable is null");
            return (Criteria) this;
        }

        public Criteria andIsnullableIsNotNull() {
            addCriterion("isnullable is not null");
            return (Criteria) this;
        }

        public Criteria andIsnullableEqualTo(String value) {
            addCriterion("isnullable =", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableNotEqualTo(String value) {
            addCriterion("isnullable <>", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableGreaterThan(String value) {
            addCriterion("isnullable >", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableGreaterThanOrEqualTo(String value) {
            addCriterion("isnullable >=", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableLessThan(String value) {
            addCriterion("isnullable <", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableLessThanOrEqualTo(String value) {
            addCriterion("isnullable <=", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableLike(String value) {
            addCriterion("isnullable like", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableNotLike(String value) {
            addCriterion("isnullable not like", value, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableIn(List<String> values) {
            addCriterion("isnullable in", values, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableNotIn(List<String> values) {
            addCriterion("isnullable not in", values, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableBetween(String value1, String value2) {
            addCriterion("isnullable between", value1, value2, "isnullable");
            return (Criteria) this;
        }

        public Criteria andIsnullableNotBetween(String value1, String value2) {
            addCriterion("isnullable not between", value1, value2, "isnullable");
            return (Criteria) this;
        }

        public Criteria andExtraIsNull() {
            addCriterion("extra is null");
            return (Criteria) this;
        }

        public Criteria andExtraIsNotNull() {
            addCriterion("extra is not null");
            return (Criteria) this;
        }

        public Criteria andExtraEqualTo(String value) {
            addCriterion("extra =", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotEqualTo(String value) {
            addCriterion("extra <>", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThan(String value) {
            addCriterion("extra >", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThanOrEqualTo(String value) {
            addCriterion("extra >=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThan(String value) {
            addCriterion("extra <", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThanOrEqualTo(String value) {
            addCriterion("extra <=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLike(String value) {
            addCriterion("extra like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotLike(String value) {
            addCriterion("extra not like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraIn(List<String> values) {
            addCriterion("extra in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotIn(List<String> values) {
            addCriterion("extra not in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraBetween(String value1, String value2) {
            addCriterion("extra between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotBetween(String value1, String value2) {
            addCriterion("extra not between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andColumncommentIsNull() {
            addCriterion("columncomment is null");
            return (Criteria) this;
        }

        public Criteria andColumncommentIsNotNull() {
            addCriterion("columncomment is not null");
            return (Criteria) this;
        }

        public Criteria andColumncommentEqualTo(String value) {
            addCriterion("columncomment =", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentNotEqualTo(String value) {
            addCriterion("columncomment <>", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentGreaterThan(String value) {
            addCriterion("columncomment >", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentGreaterThanOrEqualTo(String value) {
            addCriterion("columncomment >=", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentLessThan(String value) {
            addCriterion("columncomment <", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentLessThanOrEqualTo(String value) {
            addCriterion("columncomment <=", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentLike(String value) {
            addCriterion("columncomment like", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentNotLike(String value) {
            addCriterion("columncomment not like", value, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentIn(List<String> values) {
            addCriterion("columncomment in", values, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentNotIn(List<String> values) {
            addCriterion("columncomment not in", values, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentBetween(String value1, String value2) {
            addCriterion("columncomment between", value1, value2, "columncomment");
            return (Criteria) this;
        }

        public Criteria andColumncommentNotBetween(String value1, String value2) {
            addCriterion("columncomment not between", value1, value2, "columncomment");
            return (Criteria) this;
        }

        public Criteria andTablerowsIsNull() {
            addCriterion("tablerows is null");
            return (Criteria) this;
        }

        public Criteria andTablerowsIsNotNull() {
            addCriterion("tablerows is not null");
            return (Criteria) this;
        }

        public Criteria andTablerowsEqualTo(Long value) {
            addCriterion("tablerows =", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsNotEqualTo(Long value) {
            addCriterion("tablerows <>", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsGreaterThan(Long value) {
            addCriterion("tablerows >", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsGreaterThanOrEqualTo(Long value) {
            addCriterion("tablerows >=", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsLessThan(Long value) {
            addCriterion("tablerows <", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsLessThanOrEqualTo(Long value) {
            addCriterion("tablerows <=", value, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsIn(List<Long> values) {
            addCriterion("tablerows in", values, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsNotIn(List<Long> values) {
            addCriterion("tablerows not in", values, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsBetween(Long value1, Long value2) {
            addCriterion("tablerows between", value1, value2, "tablerows");
            return (Criteria) this;
        }

        public Criteria andTablerowsNotBetween(Long value1, Long value2) {
            addCriterion("tablerows not between", value1, value2, "tablerows");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwtableinfo
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 16 21:06:46 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}