package com.ultarischool.vwtableinfo;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ultarischool.vwtableinfo.*;


@SuppressWarnings("unused")
public interface vwtableinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int countByExample(vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int deleteByExample(vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int insert(vwtableinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int insertSelective(vwtableinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    List<vwtableinfoWithBLOBs> selectByExampleWithBLOBs(vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    List<vwtableinfo> selectByExample(vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int updateByExampleSelective(@Param("record") vwtableinfoWithBLOBs record, @Param("example") vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") vwtableinfoWithBLOBs record, @Param("example") vwtableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwtableinfo
     *
     * @mbg.generated Thu Jan 16 21:06:46 KST 2020
     */
    int updateByExample(@Param("record") vwtableinfo record, @Param("example") vwtableinfoExample example);
}