package com.ultarischool.utprogram;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class utpdetailExample extends  PageVO{
	
	private int utpsn = 0;
	
    public int getUtpsn() {
		return utpsn;
	}

	public void setUtpsn(int utpsn) {
		this.utpsn = utpsn;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public utpdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUtpsnIsNull() {
            addCriterion("utpsn is null");
            return (Criteria) this;
        }

        public Criteria andUtpsnIsNotNull() {
            addCriterion("utpsn is not null");
            return (Criteria) this;
        }

        public Criteria andUtpsnEqualTo(Integer value) {
            addCriterion("utpsn =", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnNotEqualTo(Integer value) {
            addCriterion("utpsn <>", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnGreaterThan(Integer value) {
            addCriterion("utpsn >", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnGreaterThanOrEqualTo(Integer value) {
            addCriterion("utpsn >=", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnLessThan(Integer value) {
            addCriterion("utpsn <", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnLessThanOrEqualTo(Integer value) {
            addCriterion("utpsn <=", value, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnIn(List<Integer> values) {
            addCriterion("utpsn in", values, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnNotIn(List<Integer> values) {
            addCriterion("utpsn not in", values, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnBetween(Integer value1, Integer value2) {
            addCriterion("utpsn between", value1, value2, "utpsn");
            return (Criteria) this;
        }

        public Criteria andUtpsnNotBetween(Integer value1, Integer value2) {
            addCriterion("utpsn not between", value1, value2, "utpsn");
            return (Criteria) this;
        }

        public Criteria andChasiIsNull() {
            addCriterion("chasi is null");
            return (Criteria) this;
        }

        public Criteria andChasiIsNotNull() {
            addCriterion("chasi is not null");
            return (Criteria) this;
        }

        public Criteria andChasiEqualTo(String value) {
            addCriterion("chasi =", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiNotEqualTo(String value) {
            addCriterion("chasi <>", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiGreaterThan(String value) {
            addCriterion("chasi >", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiGreaterThanOrEqualTo(String value) {
            addCriterion("chasi >=", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiLessThan(String value) {
            addCriterion("chasi <", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiLessThanOrEqualTo(String value) {
            addCriterion("chasi <=", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiLike(String value) {
            addCriterion("chasi like", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiNotLike(String value) {
            addCriterion("chasi not like", value, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiIn(List<String> values) {
            addCriterion("chasi in", values, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiNotIn(List<String> values) {
            addCriterion("chasi not in", values, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiBetween(String value1, String value2) {
            addCriterion("chasi between", value1, value2, "chasi");
            return (Criteria) this;
        }

        public Criteria andChasiNotBetween(String value1, String value2) {
            addCriterion("chasi not between", value1, value2, "chasi");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andContIsNull() {
            addCriterion("cont is null");
            return (Criteria) this;
        }

        public Criteria andContIsNotNull() {
            addCriterion("cont is not null");
            return (Criteria) this;
        }

        public Criteria andContEqualTo(String value) {
            addCriterion("cont =", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContNotEqualTo(String value) {
            addCriterion("cont <>", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContGreaterThan(String value) {
            addCriterion("cont >", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContGreaterThanOrEqualTo(String value) {
            addCriterion("cont >=", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContLessThan(String value) {
            addCriterion("cont <", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContLessThanOrEqualTo(String value) {
            addCriterion("cont <=", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContLike(String value) {
            addCriterion("cont like", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContNotLike(String value) {
            addCriterion("cont not like", value, "cont");
            return (Criteria) this;
        }

        public Criteria andContIn(List<String> values) {
            addCriterion("cont in", values, "cont");
            return (Criteria) this;
        }

        public Criteria andContNotIn(List<String> values) {
            addCriterion("cont not in", values, "cont");
            return (Criteria) this;
        }

        public Criteria andContBetween(String value1, String value2) {
            addCriterion("cont between", value1, value2, "cont");
            return (Criteria) this;
        }

        public Criteria andContNotBetween(String value1, String value2) {
            addCriterion("cont not between", value1, value2, "cont");
            return (Criteria) this;
        }

        public Criteria andBigoIsNull() {
            addCriterion("bigo is null");
            return (Criteria) this;
        }

        public Criteria andBigoIsNotNull() {
            addCriterion("bigo is not null");
            return (Criteria) this;
        }

        public Criteria andBigoEqualTo(String value) {
            addCriterion("bigo =", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoNotEqualTo(String value) {
            addCriterion("bigo <>", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoGreaterThan(String value) {
            addCriterion("bigo >", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoGreaterThanOrEqualTo(String value) {
            addCriterion("bigo >=", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoLessThan(String value) {
            addCriterion("bigo <", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoLessThanOrEqualTo(String value) {
            addCriterion("bigo <=", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoLike(String value) {
            addCriterion("bigo like", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoNotLike(String value) {
            addCriterion("bigo not like", value, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoIn(List<String> values) {
            addCriterion("bigo in", values, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoNotIn(List<String> values) {
            addCriterion("bigo not in", values, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoBetween(String value1, String value2) {
            addCriterion("bigo between", value1, value2, "bigo");
            return (Criteria) this;
        }

        public Criteria andBigoNotBetween(String value1, String value2) {
            addCriterion("bigo not between", value1, value2, "bigo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utpdetail
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 05 12:51:44 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table utpdetail
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}