package com.ultarischool.utprogram;


public class utpdetail {
    
	private String oldchasi = "";
	
	public String getOldchasi() {
		return oldchasi;
	}

	public void setOldchasi(String oldchasi) {
		this.oldchasi = oldchasi;
	}

	private String newchasi = "";
	
	public String getNewchasi() {
		return newchasi;
	}

	public void setNewchasi(String newchasi) {
		this.newchasi = newchasi;
	}

	/**
	 * 프로그램 명
	 */
	private String protitle = "";
	
	public String getProtitle() {
		return protitle;
	}

	public void setProtitle(String protitle) {
		this.protitle = protitle;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpdetail.utpsn
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    private Integer utpsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpdetail.chasi
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    private String chasi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpdetail.subject
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpdetail.cont
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    private String cont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utpdetail.bigo
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    private String bigo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpdetail.utpsn
     *
     * @return the value of utpdetail.utpsn
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public Integer getUtpsn() {
        return utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpdetail.utpsn
     *
     * @param utpsn the value for utpdetail.utpsn
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setUtpsn(Integer utpsn) {
        this.utpsn = utpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpdetail.chasi
     *
     * @return the value of utpdetail.chasi
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public String getChasi() {
        return chasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpdetail.chasi
     *
     * @param chasi the value for utpdetail.chasi
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setChasi(String chasi) {
        this.chasi = chasi == null ? null : chasi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpdetail.subject
     *
     * @return the value of utpdetail.subject
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpdetail.subject
     *
     * @param subject the value for utpdetail.subject
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpdetail.cont
     *
     * @return the value of utpdetail.cont
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpdetail.cont
     *
     * @param cont the value for utpdetail.cont
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setCont(String cont) {
        this.cont = cont == null ? null : cont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utpdetail.bigo
     *
     * @return the value of utpdetail.bigo
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public String getBigo() {
        return bigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utpdetail.bigo
     *
     * @param bigo the value for utpdetail.bigo
     *
     * @mbg.generated Sun Jan 05 12:51:44 KST 2020
     */
    public void setBigo(String bigo) {
        this.bigo = bigo == null ? null : bigo.trim();
    }
}