package com.ultarischool.utprogram;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface utprogramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(utprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(utprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(utprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(utprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    List<utprogram> selectByExample(utprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    utprogram selectByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExampleSelective(@Param("record") utprogram record, @Param("example") utprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") utprogram record, @Param("example") utprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(utprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utprogram
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(utprogram record);
}