package com.ultarischool.codet;

import edumgt.common.util.PageVO;

public class codet extends  PageVO{
    
	private String price;
	
	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getKjcode() {
		return kjcode;
	}

	public void setKjcode(String kjcode) {
		this.kjcode = kjcode;
	}

	private String kjcode;
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codet.sn
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codet.code
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codet.category
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codet.cname
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codet.cdesc
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    private String cdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codet.sn
     *
     * @return the value of codet.sn
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codet.sn
     *
     * @param sn the value for codet.sn
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codet.code
     *
     * @return the value of codet.code
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codet.code
     *
     * @param code the value for codet.code
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codet.category
     *
     * @return the value of codet.category
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codet.category
     *
     * @param category the value for codet.category
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codet.cname
     *
     * @return the value of codet.cname
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codet.cname
     *
     * @param cname the value for codet.cname
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codet.cdesc
     *
     * @return the value of codet.cdesc
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codet.cdesc
     *
     * @param cdesc the value for codet.cdesc
     *
     * @mbg.generated Wed Jan 01 16:40:50 KST 2020
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc == null ? null : cdesc.trim();
    }
}