package com.ultarischool.etcgo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface etcgoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(etcgoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(etcgoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(etcgo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(etcgo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    List<etcgo> selectByExample(etcgoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    etcgo selectByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExampleSelective(@Param("record") etcgo record, @Param("example") etcgoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") etcgo record, @Param("example") etcgoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(etcgo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(etcgo record);
}