package com.ultarischool.etcgo;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class etcgoExample extends  PageVO{
    
	private String elsname = "";
	
	public String getElsname() {
		return elsname;
	}

	public void setElsname(String elsname) {
		this.elsname = elsname;
	}

	private String gubun = "";
	public String getGubun() {
		return gubun;
	}

	public void setGubun(String gubun) {
		this.gubun = gubun;
	}

	public String getSidogoname() {
		return sidogoname;
	}

	public void setSidogoname(String sidogoname) {
		this.sidogoname = sidogoname;
	}

	private String sidogoname = "";
	
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public etcgoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(Integer value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(Integer value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(Integer value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(Integer value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(Integer value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<Integer> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<Integer> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(Integer value1, Integer value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(Integer value1, Integer value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSvnameIsNull() {
            addCriterion("svname is null");
            return (Criteria) this;
        }

        public Criteria andSvnameIsNotNull() {
            addCriterion("svname is not null");
            return (Criteria) this;
        }

        public Criteria andSvnameEqualTo(String value) {
            addCriterion("svname =", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameNotEqualTo(String value) {
            addCriterion("svname <>", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameGreaterThan(String value) {
            addCriterion("svname >", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameGreaterThanOrEqualTo(String value) {
            addCriterion("svname >=", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameLessThan(String value) {
            addCriterion("svname <", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameLessThanOrEqualTo(String value) {
            addCriterion("svname <=", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameLike(String value) {
            addCriterion("svname like", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameNotLike(String value) {
            addCriterion("svname not like", value, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameIn(List<String> values) {
            addCriterion("svname in", values, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameNotIn(List<String> values) {
            addCriterion("svname not in", values, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameBetween(String value1, String value2) {
            addCriterion("svname between", value1, value2, "svname");
            return (Criteria) this;
        }

        public Criteria andSvnameNotBetween(String value1, String value2) {
            addCriterion("svname not between", value1, value2, "svname");
            return (Criteria) this;
        }

        public Criteria andSvtypeIsNull() {
            addCriterion("svtype is null");
            return (Criteria) this;
        }

        public Criteria andSvtypeIsNotNull() {
            addCriterion("svtype is not null");
            return (Criteria) this;
        }

        public Criteria andSvtypeEqualTo(String value) {
            addCriterion("svtype =", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeNotEqualTo(String value) {
            addCriterion("svtype <>", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeGreaterThan(String value) {
            addCriterion("svtype >", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeGreaterThanOrEqualTo(String value) {
            addCriterion("svtype >=", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeLessThan(String value) {
            addCriterion("svtype <", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeLessThanOrEqualTo(String value) {
            addCriterion("svtype <=", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeLike(String value) {
            addCriterion("svtype like", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeNotLike(String value) {
            addCriterion("svtype not like", value, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeIn(List<String> values) {
            addCriterion("svtype in", values, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeNotIn(List<String> values) {
            addCriterion("svtype not in", values, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeBetween(String value1, String value2) {
            addCriterion("svtype between", value1, value2, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvtypeNotBetween(String value1, String value2) {
            addCriterion("svtype not between", value1, value2, "svtype");
            return (Criteria) this;
        }

        public Criteria andSvmemoIsNull() {
            addCriterion("svmemo is null");
            return (Criteria) this;
        }

        public Criteria andSvmemoIsNotNull() {
            addCriterion("svmemo is not null");
            return (Criteria) this;
        }

        public Criteria andSvmemoEqualTo(String value) {
            addCriterion("svmemo =", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoNotEqualTo(String value) {
            addCriterion("svmemo <>", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoGreaterThan(String value) {
            addCriterion("svmemo >", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoGreaterThanOrEqualTo(String value) {
            addCriterion("svmemo >=", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoLessThan(String value) {
            addCriterion("svmemo <", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoLessThanOrEqualTo(String value) {
            addCriterion("svmemo <=", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoLike(String value) {
            addCriterion("svmemo like", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoNotLike(String value) {
            addCriterion("svmemo not like", value, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoIn(List<String> values) {
            addCriterion("svmemo in", values, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoNotIn(List<String> values) {
            addCriterion("svmemo not in", values, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoBetween(String value1, String value2) {
            addCriterion("svmemo between", value1, value2, "svmemo");
            return (Criteria) this;
        }

        public Criteria andSvmemoNotBetween(String value1, String value2) {
            addCriterion("svmemo not between", value1, value2, "svmemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table survey
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}