package com.khsmart.surveypool;

import java.util.ArrayList;
import java.util.List;

import edumgt.common.util.PageVO;

public class surveypoolExampleNml extends  PageVO{
    
	private Integer isvyno;
	
	public Integer getIsvyno() {
		return isvyno;
	}

	public void setIsvyno(Integer isvyno) {
		this.isvyno = isvyno;
	}

	public String getSvtype() {
		return svtype;
	}

	public void setSvtype(String svtype) {
		this.svtype = svtype;
	}

	private String svtype;
	
	private String uuid;
	
	
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	private String svyno = "";
	
	public String getSvyno() {
		return svyno;
	}

	public void setSvyno(String svyno) {
		this.svyno = svyno;
	}

	
    protected String orderByClause;

    
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected List<Criteria> oredCriteria;

    
    public surveypoolExampleNml() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(Integer value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(Integer value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(Integer value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(Integer value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(Integer value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<Integer> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<Integer> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(Integer value1, Integer value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(Integer value1, Integer value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andType1IsNull() {
            addCriterion("type1 is null");
            return (Criteria) this;
        }

        public Criteria andType1IsNotNull() {
            addCriterion("type1 is not null");
            return (Criteria) this;
        }

        public Criteria andType1EqualTo(String value) {
            addCriterion("type1 =", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotEqualTo(String value) {
            addCriterion("type1 <>", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThan(String value) {
            addCriterion("type1 >", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThanOrEqualTo(String value) {
            addCriterion("type1 >=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThan(String value) {
            addCriterion("type1 <", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThanOrEqualTo(String value) {
            addCriterion("type1 <=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Like(String value) {
            addCriterion("type1 like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotLike(String value) {
            addCriterion("type1 not like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1In(List<String> values) {
            addCriterion("type1 in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotIn(List<String> values) {
            addCriterion("type1 not in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Between(String value1, String value2) {
            addCriterion("type1 between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotBetween(String value1, String value2) {
            addCriterion("type1 not between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andBogi1IsNull() {
            addCriterion("bogi1 is null");
            return (Criteria) this;
        }

        public Criteria andBogi1IsNotNull() {
            addCriterion("bogi1 is not null");
            return (Criteria) this;
        }

        public Criteria andBogi1EqualTo(String value) {
            addCriterion("bogi1 =", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1NotEqualTo(String value) {
            addCriterion("bogi1 <>", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1GreaterThan(String value) {
            addCriterion("bogi1 >", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1GreaterThanOrEqualTo(String value) {
            addCriterion("bogi1 >=", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1LessThan(String value) {
            addCriterion("bogi1 <", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1LessThanOrEqualTo(String value) {
            addCriterion("bogi1 <=", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1Like(String value) {
            addCriterion("bogi1 like", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1NotLike(String value) {
            addCriterion("bogi1 not like", value, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1In(List<String> values) {
            addCriterion("bogi1 in", values, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1NotIn(List<String> values) {
            addCriterion("bogi1 not in", values, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1Between(String value1, String value2) {
            addCriterion("bogi1 between", value1, value2, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi1NotBetween(String value1, String value2) {
            addCriterion("bogi1 not between", value1, value2, "bogi1");
            return (Criteria) this;
        }

        public Criteria andBogi2IsNull() {
            addCriterion("bogi2 is null");
            return (Criteria) this;
        }

        public Criteria andBogi2IsNotNull() {
            addCriterion("bogi2 is not null");
            return (Criteria) this;
        }

        public Criteria andBogi2EqualTo(String value) {
            addCriterion("bogi2 =", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2NotEqualTo(String value) {
            addCriterion("bogi2 <>", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2GreaterThan(String value) {
            addCriterion("bogi2 >", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2GreaterThanOrEqualTo(String value) {
            addCriterion("bogi2 >=", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2LessThan(String value) {
            addCriterion("bogi2 <", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2LessThanOrEqualTo(String value) {
            addCriterion("bogi2 <=", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2Like(String value) {
            addCriterion("bogi2 like", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2NotLike(String value) {
            addCriterion("bogi2 not like", value, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2In(List<String> values) {
            addCriterion("bogi2 in", values, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2NotIn(List<String> values) {
            addCriterion("bogi2 not in", values, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2Between(String value1, String value2) {
            addCriterion("bogi2 between", value1, value2, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi2NotBetween(String value1, String value2) {
            addCriterion("bogi2 not between", value1, value2, "bogi2");
            return (Criteria) this;
        }

        public Criteria andBogi3IsNull() {
            addCriterion("bogi3 is null");
            return (Criteria) this;
        }

        public Criteria andBogi3IsNotNull() {
            addCriterion("bogi3 is not null");
            return (Criteria) this;
        }

        public Criteria andBogi3EqualTo(String value) {
            addCriterion("bogi3 =", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3NotEqualTo(String value) {
            addCriterion("bogi3 <>", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3GreaterThan(String value) {
            addCriterion("bogi3 >", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3GreaterThanOrEqualTo(String value) {
            addCriterion("bogi3 >=", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3LessThan(String value) {
            addCriterion("bogi3 <", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3LessThanOrEqualTo(String value) {
            addCriterion("bogi3 <=", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3Like(String value) {
            addCriterion("bogi3 like", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3NotLike(String value) {
            addCriterion("bogi3 not like", value, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3In(List<String> values) {
            addCriterion("bogi3 in", values, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3NotIn(List<String> values) {
            addCriterion("bogi3 not in", values, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3Between(String value1, String value2) {
            addCriterion("bogi3 between", value1, value2, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi3NotBetween(String value1, String value2) {
            addCriterion("bogi3 not between", value1, value2, "bogi3");
            return (Criteria) this;
        }

        public Criteria andBogi4IsNull() {
            addCriterion("bogi4 is null");
            return (Criteria) this;
        }

        public Criteria andBogi4IsNotNull() {
            addCriterion("bogi4 is not null");
            return (Criteria) this;
        }

        public Criteria andBogi4EqualTo(String value) {
            addCriterion("bogi4 =", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4NotEqualTo(String value) {
            addCriterion("bogi4 <>", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4GreaterThan(String value) {
            addCriterion("bogi4 >", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4GreaterThanOrEqualTo(String value) {
            addCriterion("bogi4 >=", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4LessThan(String value) {
            addCriterion("bogi4 <", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4LessThanOrEqualTo(String value) {
            addCriterion("bogi4 <=", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4Like(String value) {
            addCriterion("bogi4 like", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4NotLike(String value) {
            addCriterion("bogi4 not like", value, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4In(List<String> values) {
            addCriterion("bogi4 in", values, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4NotIn(List<String> values) {
            addCriterion("bogi4 not in", values, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4Between(String value1, String value2) {
            addCriterion("bogi4 between", value1, value2, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi4NotBetween(String value1, String value2) {
            addCriterion("bogi4 not between", value1, value2, "bogi4");
            return (Criteria) this;
        }

        public Criteria andBogi5IsNull() {
            addCriterion("bogi5 is null");
            return (Criteria) this;
        }

        public Criteria andBogi5IsNotNull() {
            addCriterion("bogi5 is not null");
            return (Criteria) this;
        }

        public Criteria andBogi5EqualTo(String value) {
            addCriterion("bogi5 =", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5NotEqualTo(String value) {
            addCriterion("bogi5 <>", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5GreaterThan(String value) {
            addCriterion("bogi5 >", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5GreaterThanOrEqualTo(String value) {
            addCriterion("bogi5 >=", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5LessThan(String value) {
            addCriterion("bogi5 <", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5LessThanOrEqualTo(String value) {
            addCriterion("bogi5 <=", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5Like(String value) {
            addCriterion("bogi5 like", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5NotLike(String value) {
            addCriterion("bogi5 not like", value, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5In(List<String> values) {
            addCriterion("bogi5 in", values, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5NotIn(List<String> values) {
            addCriterion("bogi5 not in", values, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5Between(String value1, String value2) {
            addCriterion("bogi5 between", value1, value2, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi5NotBetween(String value1, String value2) {
            addCriterion("bogi5 not between", value1, value2, "bogi5");
            return (Criteria) this;
        }

        public Criteria andBogi1jumIsNull() {
            addCriterion("bogi1jum is null");
            return (Criteria) this;
        }

        public Criteria andBogi1jumIsNotNull() {
            addCriterion("bogi1jum is not null");
            return (Criteria) this;
        }

        public Criteria andBogi1jumEqualTo(Integer value) {
            addCriterion("bogi1jum =", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumNotEqualTo(Integer value) {
            addCriterion("bogi1jum <>", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumGreaterThan(Integer value) {
            addCriterion("bogi1jum >", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bogi1jum >=", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumLessThan(Integer value) {
            addCriterion("bogi1jum <", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumLessThanOrEqualTo(Integer value) {
            addCriterion("bogi1jum <=", value, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumIn(List<Integer> values) {
            addCriterion("bogi1jum in", values, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumNotIn(List<Integer> values) {
            addCriterion("bogi1jum not in", values, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumBetween(Integer value1, Integer value2) {
            addCriterion("bogi1jum between", value1, value2, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi1jumNotBetween(Integer value1, Integer value2) {
            addCriterion("bogi1jum not between", value1, value2, "bogi1jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumIsNull() {
            addCriterion("bogi2jum is null");
            return (Criteria) this;
        }

        public Criteria andBogi2jumIsNotNull() {
            addCriterion("bogi2jum is not null");
            return (Criteria) this;
        }

        public Criteria andBogi2jumEqualTo(Integer value) {
            addCriterion("bogi2jum =", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumNotEqualTo(Integer value) {
            addCriterion("bogi2jum <>", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumGreaterThan(Integer value) {
            addCriterion("bogi2jum >", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bogi2jum >=", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumLessThan(Integer value) {
            addCriterion("bogi2jum <", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumLessThanOrEqualTo(Integer value) {
            addCriterion("bogi2jum <=", value, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumIn(List<Integer> values) {
            addCriterion("bogi2jum in", values, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumNotIn(List<Integer> values) {
            addCriterion("bogi2jum not in", values, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumBetween(Integer value1, Integer value2) {
            addCriterion("bogi2jum between", value1, value2, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi2jumNotBetween(Integer value1, Integer value2) {
            addCriterion("bogi2jum not between", value1, value2, "bogi2jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumIsNull() {
            addCriterion("bogi3jum is null");
            return (Criteria) this;
        }

        public Criteria andBogi3jumIsNotNull() {
            addCriterion("bogi3jum is not null");
            return (Criteria) this;
        }

        public Criteria andBogi3jumEqualTo(Integer value) {
            addCriterion("bogi3jum =", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumNotEqualTo(Integer value) {
            addCriterion("bogi3jum <>", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumGreaterThan(Integer value) {
            addCriterion("bogi3jum >", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bogi3jum >=", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumLessThan(Integer value) {
            addCriterion("bogi3jum <", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumLessThanOrEqualTo(Integer value) {
            addCriterion("bogi3jum <=", value, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumIn(List<Integer> values) {
            addCriterion("bogi3jum in", values, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumNotIn(List<Integer> values) {
            addCriterion("bogi3jum not in", values, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumBetween(Integer value1, Integer value2) {
            addCriterion("bogi3jum between", value1, value2, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi3jumNotBetween(Integer value1, Integer value2) {
            addCriterion("bogi3jum not between", value1, value2, "bogi3jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumIsNull() {
            addCriterion("bogi4jum is null");
            return (Criteria) this;
        }

        public Criteria andBogi4jumIsNotNull() {
            addCriterion("bogi4jum is not null");
            return (Criteria) this;
        }

        public Criteria andBogi4jumEqualTo(Integer value) {
            addCriterion("bogi4jum =", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumNotEqualTo(Integer value) {
            addCriterion("bogi4jum <>", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumGreaterThan(Integer value) {
            addCriterion("bogi4jum >", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bogi4jum >=", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumLessThan(Integer value) {
            addCriterion("bogi4jum <", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumLessThanOrEqualTo(Integer value) {
            addCriterion("bogi4jum <=", value, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumIn(List<Integer> values) {
            addCriterion("bogi4jum in", values, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumNotIn(List<Integer> values) {
            addCriterion("bogi4jum not in", values, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumBetween(Integer value1, Integer value2) {
            addCriterion("bogi4jum between", value1, value2, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi4jumNotBetween(Integer value1, Integer value2) {
            addCriterion("bogi4jum not between", value1, value2, "bogi4jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumIsNull() {
            addCriterion("bogi5jum is null");
            return (Criteria) this;
        }

        public Criteria andBogi5jumIsNotNull() {
            addCriterion("bogi5jum is not null");
            return (Criteria) this;
        }

        public Criteria andBogi5jumEqualTo(Integer value) {
            addCriterion("bogi5jum =", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumNotEqualTo(Integer value) {
            addCriterion("bogi5jum <>", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumGreaterThan(Integer value) {
            addCriterion("bogi5jum >", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bogi5jum >=", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumLessThan(Integer value) {
            addCriterion("bogi5jum <", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumLessThanOrEqualTo(Integer value) {
            addCriterion("bogi5jum <=", value, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumIn(List<Integer> values) {
            addCriterion("bogi5jum in", values, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumNotIn(List<Integer> values) {
            addCriterion("bogi5jum not in", values, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumBetween(Integer value1, Integer value2) {
            addCriterion("bogi5jum between", value1, value2, "bogi5jum");
            return (Criteria) this;
        }

        public Criteria andBogi5jumNotBetween(Integer value1, Integer value2) {
            addCriterion("bogi5jum not between", value1, value2, "bogi5jum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table surveypool
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}