package com.ultarischool.career;

public class career {
    
	
	private String faqhdr;
	public String getFaqhdr() {
		return faqhdr;
	}

	public void setFaqhdr(String faqhdr) {
		this.faqhdr = faqhdr;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Integer getOdrno() {
		return odrno;
	}

	public void setOdrno(Integer odrno) {
		this.odrno = odrno;
	}

	public String getMp4url() {
		return mp4url;
	}

	public void setMp4url(String mp4url) {
		this.mp4url = mp4url;
	}

	public String getYtburl() {
		return ytburl;
	}

	public void setYtburl(String ytburl) {
		this.ytburl = ytburl;
	}

	private String question;
	private String answer;
	private Integer odrno;
	private String mp4url;
	private String ytburl;
	
	
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.useridfk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String useridfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.crtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String crtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.crtypeodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer crtypeodrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.sdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.edate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String edate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.gradu
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String gradu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.jikham
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String jikham;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.jikchk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String jikchk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String memo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String memo2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.sn
     *
     * @return the value of career.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.sn
     *
     * @param sn the value for career.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.useridfk
     *
     * @return the value of career.useridfk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getUseridfk() {
        return useridfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.useridfk
     *
     * @param useridfk the value for career.useridfk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setUseridfk(String useridfk) {
        this.useridfk = useridfk == null ? null : useridfk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.crtype
     *
     * @return the value of career.crtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getCrtype() {
        return crtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.crtype
     *
     * @param crtype the value for career.crtype
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setCrtype(String crtype) {
        this.crtype = crtype == null ? null : crtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.crtypeodrno
     *
     * @return the value of career.crtypeodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getCrtypeodrno() {
        return crtypeodrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.crtypeodrno
     *
     * @param crtypeodrno the value for career.crtypeodrno
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setCrtypeodrno(Integer crtypeodrno) {
        this.crtypeodrno = crtypeodrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.title
     *
     * @return the value of career.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.title
     *
     * @param title the value for career.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.subtitle
     *
     * @return the value of career.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.subtitle
     *
     * @param subtitle the value for career.subtitle
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.sdate
     *
     * @return the value of career.sdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.sdate
     *
     * @param sdate the value for career.sdate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSdate(String sdate) {
        this.sdate = sdate == null ? null : sdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.edate
     *
     * @return the value of career.edate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.edate
     *
     * @param edate the value for career.edate
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setEdate(String edate) {
        this.edate = edate == null ? null : edate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.gradu
     *
     * @return the value of career.gradu
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getGradu() {
        return gradu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.gradu
     *
     * @param gradu the value for career.gradu
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setGradu(String gradu) {
        this.gradu = gradu == null ? null : gradu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.jikham
     *
     * @return the value of career.jikham
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getJikham() {
        return jikham;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.jikham
     *
     * @param jikham the value for career.jikham
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setJikham(String jikham) {
        this.jikham = jikham == null ? null : jikham.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.jikchk
     *
     * @return the value of career.jikchk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getJikchk() {
        return jikchk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.jikchk
     *
     * @param jikchk the value for career.jikchk
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setJikchk(String jikchk) {
        this.jikchk = jikchk == null ? null : jikchk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.memo1
     *
     * @return the value of career.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.memo1
     *
     * @param memo1 the value for career.memo1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.memo2
     *
     * @return the value of career.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.memo2
     *
     * @param memo2 the value for career.memo2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2 == null ? null : memo2.trim();
    }
}