package com.ultarischool.surveypool;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface surveypoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(surveypoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(surveypoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(surveypool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(surveypool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    List<surveypool> selectByExample(surveypoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    surveypool selectByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExampleSelective(@Param("record") surveypool record, @Param("example") surveypoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") surveypool record, @Param("example") surveypoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(surveypool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveypool
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(surveypool record);
    
    int updateBySn(surveypool surveypool);
    
    List<surveypool> getSurveypoolListBySvyno(int svyno);
}