package com.ultarischool.surveypool;

public class surveypool {

	private String smcnt;
	private String svytypename;
	private String ctudsn = "";
	private String svname;
	private String svtype;
	private String svyno;
	private String odrno;
	private String svmemo;
	private Integer sn;
	private String title;
	private String type1;
	private String bogi1;
	private String bogi2;
	private String bogi3;
	private String bogi4;
	private String bogi5;
	private String bogi6;
	private String bogi7;
	private String bogi8;
	private String bogi9;
	private String bogi10;
	private String bogi11;
	private String bogi12;
	private String bogi13;
	private String bogi14;
	private String bogi15;
	private String bogi16;
	private String bogi17;
	private String bogi18;
	private String bogi19;
	private String bogi20;
	private String bogi1type;
	private String bogi2type;
	private String bogi3type;
	private String bogi4type;
	private String bogi5type;
	private String bogi6type;
	private String bogi7type;
	private String bogi8type;
	private String bogi9type;
	private String bogi10type;
	private String bogi11type;
	private String bogi12type;
	private String bogi13type;
	private String bogi14type;
	private String bogi15type;
	private String bogi16type;
	private String bogi17type;
	private String bogi18type;
	private String bogi19type;
	private String bogi20type;
	private Integer bogi1jum;
	private Integer bogi2jum;
	private Integer bogi3jum;
	private Integer bogi4jum;
	private Integer bogi5jum;

	public String getSmcnt() {
		return smcnt;
	}

	public void setSmcnt(String smcnt) {
		this.smcnt = smcnt;
	}

	public String getSvytypename() {
		return svytypename;
	}

	public void setSvytypename(String svytypename) {
		this.svytypename = svytypename;
	}

	public String getCtudsn() {
		return ctudsn;
	}

	public void setCtudsn(String ctudsn) {
		this.ctudsn = ctudsn;
	}

	public String getSvname() {
		return svname;
	}

	public void setSvname(String svname) {
		this.svname = svname;
	}

	public String getSvtype() {
		return svtype;
	}

	public void setSvtype(String svtype) {
		this.svtype = svtype;
	}

	public String getSvmemo() {
		return svmemo;
	}

	public void setSvmemo(String svmemo) {
		this.svmemo = svmemo;
	}

	public String getSvyno() {
		return svyno;
	}

	public void setSvyno(String svyno) {
		this.svyno = svyno;
	}

	public String getOdrno() {
		return odrno;
	}

	public void setOdrno(String odrno) {
		this.odrno = odrno;
	}

	public Integer getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.sn
	 *
	 * @param sn the value for surveypool.sn
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setSn(Integer sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.title
	 *
	 * @return the value of surveypool.title
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.title
	 *
	 * @param title the value for surveypool.title
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.type1
	 *
	 * @return the value of surveypool.type1
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getType1() {
		return type1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.type1
	 *
	 * @param type1 the value for surveypool.type1
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setType1(String type1) {
		this.type1 = type1 == null ? null : type1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi1
	 *
	 * @return the value of surveypool.bogi1
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBogi1() {
		return bogi1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi1
	 *
	 * @param bogi1 the value for surveypool.bogi1
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi1(String bogi1) {
		this.bogi1 = bogi1 == null ? null : bogi1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi2
	 *
	 * @return the value of surveypool.bogi2
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBogi2() {
		return bogi2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi2
	 *
	 * @param bogi2 the value for surveypool.bogi2
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi2(String bogi2) {
		this.bogi2 = bogi2 == null ? null : bogi2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi3
	 *
	 * @return the value of surveypool.bogi3
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBogi3() {
		return bogi3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi3
	 *
	 * @param bogi3 the value for surveypool.bogi3
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi3(String bogi3) {
		this.bogi3 = bogi3 == null ? null : bogi3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi4
	 *
	 * @return the value of surveypool.bogi4
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBogi4() {
		return bogi4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi4
	 *
	 * @param bogi4 the value for surveypool.bogi4
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi4(String bogi4) {
		this.bogi4 = bogi4 == null ? null : bogi4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi5
	 *
	 * @return the value of surveypool.bogi5
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBogi5() {
		return bogi5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi5
	 *
	 * @param bogi5 the value for surveypool.bogi5
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi5(String bogi5) {
		this.bogi5 = bogi5 == null ? null : bogi5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi1jum
	 *
	 * @return the value of surveypool.bogi1jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getBogi1jum() {
		return bogi1jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi1jum
	 *
	 * @param bogi1jum the value for surveypool.bogi1jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi1jum(Integer bogi1jum) {
		this.bogi1jum = bogi1jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi2jum
	 *
	 * @return the value of surveypool.bogi2jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getBogi2jum() {
		return bogi2jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi2jum
	 *
	 * @param bogi2jum the value for surveypool.bogi2jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi2jum(Integer bogi2jum) {
		this.bogi2jum = bogi2jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi3jum
	 *
	 * @return the value of surveypool.bogi3jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getBogi3jum() {
		return bogi3jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi3jum
	 *
	 * @param bogi3jum the value for surveypool.bogi3jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi3jum(Integer bogi3jum) {
		this.bogi3jum = bogi3jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi4jum
	 *
	 * @return the value of surveypool.bogi4jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getBogi4jum() {
		return bogi4jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi4jum
	 *
	 * @param bogi4jum the value for surveypool.bogi4jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi4jum(Integer bogi4jum) {
		this.bogi4jum = bogi4jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column surveypool.bogi5jum
	 *
	 * @return the value of surveypool.bogi5jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getBogi5jum() {
		return bogi5jum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column surveypool.bogi5jum
	 *
	 * @param bogi5jum the value for surveypool.bogi5jum
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBogi5jum(Integer bogi5jum) {
		this.bogi5jum = bogi5jum;
	}

	public String getBogi6() {
		return bogi6;
	}

	public void setBogi6(String bogi6) {
		this.bogi6 = bogi6;
	}

	public String getBogi7() {
		return bogi7;
	}

	public void setBogi7(String bogi7) {
		this.bogi7 = bogi7;
	}

	public String getBogi8() {
		return bogi8;
	}

	public void setBogi8(String bogi8) {
		this.bogi8 = bogi8;
	}

	public String getBogi9() {
		return bogi9;
	}

	public void setBogi9(String bogi9) {
		this.bogi9 = bogi9;
	}

	public String getBogi10() {
		return bogi10;
	}

	public void setBogi10(String bogi10) {
		this.bogi10 = bogi10;
	}

	public String getBogi11() {
		return bogi11;
	}

	public void setBogi11(String bogi11) {
		this.bogi11 = bogi11;
	}

	public String getBogi12() {
		return bogi12;
	}

	public void setBogi12(String bogi12) {
		this.bogi12 = bogi12;
	}

	public String getBogi13() {
		return bogi13;
	}

	public void setBogi13(String bogi13) {
		this.bogi13 = bogi13;
	}

	public String getBogi14() {
		return bogi14;
	}

	public void setBogi14(String bogi14) {
		this.bogi14 = bogi14;
	}

	public String getBogi15() {
		return bogi15;
	}

	public void setBogi15(String bogi15) {
		this.bogi15 = bogi15;
	}

	public String getBogi16() {
		return bogi16;
	}

	public void setBogi16(String bogi16) {
		this.bogi16 = bogi16;
	}

	public String getBogi17() {
		return bogi17;
	}

	public void setBogi17(String bogi17) {
		this.bogi17 = bogi17;
	}

	public String getBogi18() {
		return bogi18;
	}

	public void setBogi18(String bogi18) {
		this.bogi18 = bogi18;
	}

	public String getBogi19() {
		return bogi19;
	}

	public void setBogi19(String bogi19) {
		this.bogi19 = bogi19;
	}

	public String getBogi20() {
		return bogi20;
	}

	public void setBogi20(String bogi20) {
		this.bogi20 = bogi20;
	}

	public String getBogi1type() {
		return bogi1type;
	}

	public void setBogi1type(String bogi1type) {
		this.bogi1type = bogi1type;
	}

	public String getBogi2type() {
		return bogi2type;
	}

	public void setBogi2type(String bogi2type) {
		this.bogi2type = bogi2type;
	}

	public String getBogi3type() {
		return bogi3type;
	}

	public void setBogi3type(String bogi3type) {
		this.bogi3type = bogi3type;
	}

	public String getBogi4type() {
		return bogi4type;
	}

	public void setBogi4type(String bogi4type) {
		this.bogi4type = bogi4type;
	}

	public String getBogi5type() {
		return bogi5type;
	}

	public void setBogi5type(String bogi5type) {
		this.bogi5type = bogi5type;
	}

	public String getBogi6type() {
		return bogi6type;
	}

	public void setBogi6type(String bogi6type) {
		this.bogi6type = bogi6type;
	}

	public String getBogi7type() {
		return bogi7type;
	}

	public void setBogi7type(String bogi7type) {
		this.bogi7type = bogi7type;
	}

	public String getBogi8type() {
		return bogi8type;
	}

	public void setBogi8type(String bogi8type) {
		this.bogi8type = bogi8type;
	}

	public String getBogi9type() {
		return bogi9type;
	}

	public void setBogi9type(String bogi9type) {
		this.bogi9type = bogi9type;
	}

	public String getBogi10type() {
		return bogi10type;
	}

	public void setBogi10type(String bogi10type) {
		this.bogi10type = bogi10type;
	}

	public String getBogi11type() {
		return bogi11type;
	}

	public void setBogi11type(String bogi11type) {
		this.bogi11type = bogi11type;
	}

	public String getBogi12type() {
		return bogi12type;
	}

	public void setBogi12type(String bogi12type) {
		this.bogi12type = bogi12type;
	}

	public String getBogi13type() {
		return bogi13type;
	}

	public void setBogi13type(String bogi13type) {
		this.bogi13type = bogi13type;
	}

	public String getBogi14type() {
		return bogi14type;
	}

	public void setBogi14type(String bogi14type) {
		this.bogi14type = bogi14type;
	}

	public String getBogi15type() {
		return bogi15type;
	}

	public void setBogi15type(String bogi15type) {
		this.bogi15type = bogi15type;
	}

	public String getBogi16type() {
		return bogi16type;
	}

	public void setBogi16type(String bogi16type) {
		this.bogi16type = bogi16type;
	}

	public String getBogi17type() {
		return bogi17type;
	}

	public void setBogi17type(String bogi17type) {
		this.bogi17type = bogi17type;
	}

	public String getBogi18type() {
		return bogi18type;
	}

	public void setBogi18type(String bogi18type) {
		this.bogi18type = bogi18type;
	}

	public String getBogi19type() {
		return bogi19type;
	}

	public void setBogi19type(String bogi19type) {
		this.bogi19type = bogi19type;
	}

	public String getBogi20type() {
		return bogi20type;
	}

	public void setBogi20type(String bogi20type) {
		this.bogi20type = bogi20type;
	}

	@Override
	public String toString() {
		return "surveypool [smcnt=" + smcnt + ", svytypename=" + svytypename + ", ctudsn=" + ctudsn + ", svname="
				+ svname + ", svtype=" + svtype + ", svyno=" + svyno + ", odrno=" + odrno + ", svmemo=" + svmemo
				+ ", sn=" + sn + ", title=" + title + ", type1=" + type1 + ", bogi1=" + bogi1 + ", bogi2=" + bogi2
				+ ", bogi3=" + bogi3 + ", bogi4=" + bogi4 + ", bogi5=" + bogi5 + ", bogi6=" + bogi6 + ", bogi7=" + bogi7
				+ ", bogi8=" + bogi8 + ", bogi9=" + bogi9 + ", bogi10=" + bogi10 + ", bogi11=" + bogi11 + ", bogi12="
				+ bogi12 + ", bogi13=" + bogi13 + ", bogi14=" + bogi14 + ", bogi15=" + bogi15 + ", bogi16=" + bogi16
				+ ", bogi17=" + bogi17 + ", bogi18=" + bogi18 + ", bogi19=" + bogi19 + ", bogi20=" + bogi20
				+ ", bogi1type=" + bogi1type + ", bogi2type=" + bogi2type + ", bogi3type=" + bogi3type + ", bogi4type="
				+ bogi4type + ", bogi5type=" + bogi5type + ", bogi6type=" + bogi6type + ", bogi7type=" + bogi7type
				+ ", bogi8type=" + bogi8type + ", bogi9type=" + bogi9type + ", bogi10type=" + bogi10type
				+ ", bogi11type=" + bogi11type + ", bogi12type=" + bogi12type + ", bogi13type=" + bogi13type
				+ ", bogi14type=" + bogi14type + ", bogi15type=" + bogi15type + ", bogi16type=" + bogi16type
				+ ", bogi17type=" + bogi17type + ", bogi18type=" + bogi18type + ", bogi19type=" + bogi19type
				+ ", bogi20type=" + bogi20type + ", bogi1jum=" + bogi1jum + ", bogi2jum=" + bogi2jum + ", bogi3jum="
				+ bogi3jum + ", bogi4jum=" + bogi4jum + ", bogi5jum=" + bogi5jum + "]";
	}

}