package com.ultarischool.surveypool;

public class surveypool {
    
	private String smcnt;
	
	public String getSmcnt() {
		return smcnt;
	}

	public void setSmcnt(String smcnt) {
		this.smcnt = smcnt;
	}

	private String svytypename;

	public String getSvytypename() {
		return svytypename;
	}

	public void setSvytypename(String svytypename) {
		this.svytypename = svytypename;
	}

	private String ctudsn = "";
	public String getCtudsn() {
		return ctudsn;
	}

	public void setCtudsn(String ctudsn) {
		this.ctudsn = ctudsn;
	}

	private String svname;
	public String getSvname() {
		return svname;
	}

	public void setSvname(String svname) {
		this.svname = svname;
	}

	public String getSvtype() {
		return svtype;
	}

	public void setSvtype(String svtype) {
		this.svtype = svtype;
	}

	public String getSvmemo() {
		return svmemo;
	}

	public void setSvmemo(String svmemo) {
		this.svmemo = svmemo;
	}

	private String svtype;
	
	public String getSvyno() {
		return svyno;
	}

	public void setSvyno(String svyno) {
		this.svyno = svyno;
	}

	public String getOdrno() {
		return odrno;
	}

	public void setOdrno(String odrno) {
		this.odrno = odrno;
	}

	private String svyno;
	private String odrno;
	
	private String svmemo;
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.type1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bogi1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bogi2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi3
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bogi3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi4
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bogi4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi5
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private String bogi5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi1jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer bogi1jum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi2jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer bogi2jum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi3jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer bogi3jum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi4jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer bogi4jum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveypool.bogi5jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    private Integer bogi5jum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.sn
     *
     * @return the value of surveypool.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.sn
     *
     * @param sn the value for surveypool.sn
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.title
     *
     * @return the value of surveypool.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.title
     *
     * @param title the value for surveypool.title
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.type1
     *
     * @return the value of surveypool.type1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.type1
     *
     * @param type1 the value for surveypool.type1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi1
     *
     * @return the value of surveypool.bogi1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBogi1() {
        return bogi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi1
     *
     * @param bogi1 the value for surveypool.bogi1
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi1(String bogi1) {
        this.bogi1 = bogi1 == null ? null : bogi1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi2
     *
     * @return the value of surveypool.bogi2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBogi2() {
        return bogi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi2
     *
     * @param bogi2 the value for surveypool.bogi2
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi2(String bogi2) {
        this.bogi2 = bogi2 == null ? null : bogi2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi3
     *
     * @return the value of surveypool.bogi3
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBogi3() {
        return bogi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi3
     *
     * @param bogi3 the value for surveypool.bogi3
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi3(String bogi3) {
        this.bogi3 = bogi3 == null ? null : bogi3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi4
     *
     * @return the value of surveypool.bogi4
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBogi4() {
        return bogi4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi4
     *
     * @param bogi4 the value for surveypool.bogi4
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi4(String bogi4) {
        this.bogi4 = bogi4 == null ? null : bogi4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi5
     *
     * @return the value of surveypool.bogi5
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public String getBogi5() {
        return bogi5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi5
     *
     * @param bogi5 the value for surveypool.bogi5
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi5(String bogi5) {
        this.bogi5 = bogi5 == null ? null : bogi5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi1jum
     *
     * @return the value of surveypool.bogi1jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getBogi1jum() {
        return bogi1jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi1jum
     *
     * @param bogi1jum the value for surveypool.bogi1jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi1jum(Integer bogi1jum) {
        this.bogi1jum = bogi1jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi2jum
     *
     * @return the value of surveypool.bogi2jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getBogi2jum() {
        return bogi2jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi2jum
     *
     * @param bogi2jum the value for surveypool.bogi2jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi2jum(Integer bogi2jum) {
        this.bogi2jum = bogi2jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi3jum
     *
     * @return the value of surveypool.bogi3jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getBogi3jum() {
        return bogi3jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi3jum
     *
     * @param bogi3jum the value for surveypool.bogi3jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi3jum(Integer bogi3jum) {
        this.bogi3jum = bogi3jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi4jum
     *
     * @return the value of surveypool.bogi4jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getBogi4jum() {
        return bogi4jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi4jum
     *
     * @param bogi4jum the value for surveypool.bogi4jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi4jum(Integer bogi4jum) {
        this.bogi4jum = bogi4jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveypool.bogi5jum
     *
     * @return the value of surveypool.bogi5jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public Integer getBogi5jum() {
        return bogi5jum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveypool.bogi5jum
     *
     * @param bogi5jum the value for surveypool.bogi5jum
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    public void setBogi5jum(Integer bogi5jum) {
        this.bogi5jum = bogi5jum;
    }
}