package com.ultarischool.surveyrelusert;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface surveyrelusertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(surveyrelusertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(surveyrelusertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(surveyrelusert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(surveyrelusert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    List<surveyrelusert> selectByExample(surveyrelusertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    surveyrelusert selectByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExampleSelective(@Param("record") surveyrelusert record, @Param("example") surveyrelusertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") surveyrelusert record, @Param("example") surveyrelusertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(surveyrelusert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyrelusert
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(surveyrelusert record);
}