package com.ultarischool.hpenv;

public class hpenv {

	private String cmsbigid;
	
	public String getCmstypename() {
		return cmstypename;
	}

	public void setCmstypename(String cmstypename) {
		this.cmstypename = cmstypename;
	}

	private String cmstypename;
	
	private String tgcode;
	public String getTgcode() {
		return tgcode;
	}

	public void setTgcode(String tgcode) {
		this.tgcode = tgcode;
	}

	public String getTgname() {
		return tgname;
	}

	public void setTgname(String tgname) {
		this.tgname = tgname;
	}

	private String tgname;
	
	private String cbtitle;

	public String getCbtitle() {
		return cbtitle;
	}

	public void setCbtitle(String cbtitle) {
		this.cbtitle = cbtitle;
	}

	public String getCmsbigid() {
		return cmsbigid;
	}

	public void setCmsbigid(String cmsbigid) {
		this.cmsbigid = cmsbigid;
	}

	public String getCourseid() {
		return courseid;
	}

	public void setCourseid(String courseid) {
		this.courseid = courseid;
	}

	private String courseid;

	private String cmstype;

	public String getCmstype() {
		return cmstype;
	}

	public void setCmstype(String cmstype) {
		this.cmstype = cmstype;
	}

	public Integer getOrd() {
		return ord;
	}

	public void setOrd(Integer ord) {
		this.ord = ord;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCmstag() {
		return cmstag;
	}

	public void setCmstag(String cmstag) {
		this.cmstag = cmstag;
	}

	private Integer ord;
	private String title;
	private String cmstag;
	private Integer sn;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.envtype
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String envtype;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.owner
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String owner;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.tel
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String tel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.addr
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String addr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.regno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String regno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.bankno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String bankno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column hpenv.etcmemo
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	private String etcmemo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.sn
	 *
	 * @return the value of hpenv.sn
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public Integer getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.sn
	 *
	 * @param sn the value for hpenv.sn
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setSn(Integer sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.envtype
	 *
	 * @return the value of hpenv.envtype
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getEnvtype() {
		return envtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.envtype
	 *
	 * @param envtype the value for hpenv.envtype
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setEnvtype(String envtype) {
		this.envtype = envtype == null ? null : envtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.owner
	 *
	 * @return the value of hpenv.owner
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.owner
	 *
	 * @param owner the value for hpenv.owner
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setOwner(String owner) {
		this.owner = owner == null ? null : owner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.tel
	 *
	 * @return the value of hpenv.tel
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.tel
	 *
	 * @param tel the value for hpenv.tel
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.addr
	 *
	 * @return the value of hpenv.addr
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.addr
	 *
	 * @param addr the value for hpenv.addr
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.regno
	 *
	 * @return the value of hpenv.regno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getRegno() {
		return regno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.regno
	 *
	 * @param regno the value for hpenv.regno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setRegno(String regno) {
		this.regno = regno == null ? null : regno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.bankno
	 *
	 * @return the value of hpenv.bankno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getBankno() {
		return bankno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.bankno
	 *
	 * @param bankno the value for hpenv.bankno
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setBankno(String bankno) {
		this.bankno = bankno == null ? null : bankno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column hpenv.etcmemo
	 *
	 * @return the value of hpenv.etcmemo
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public String getEtcmemo() {
		return etcmemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column hpenv.etcmemo
	 *
	 * @param etcmemo the value for hpenv.etcmemo
	 *
	 * @mbg.generated Tue Dec 17 11:09:48 KST 2019
	 */
	public void setEtcmemo(String etcmemo) {
		this.etcmemo = etcmemo == null ? null : etcmemo.trim();
	}
}